### ISSUE TITLE
After installation, Dimension not working due to invalid token error

### ISSUE THREAD

**Issue by briankendall** [spantaleev/matrix-docker-ansible-deploy#1271]
After bouncing around between different issues (including the one that was recently introduced and then fixed in Dimension's docker repo), I have once again run into a problem with invalid tokens and Dimension in a fresh Matrix installation.

When visiting https://dimension.mydomain.com/riot-app/admin or any other section in the Dimension web UI, the page loads and the lefthand menu appears, but the rest of the page remains blank. The following error appears in the Javascript console:

    polyfills.5b05d1f209828e3ee1a5.js:1 GET https://dimension.mydomain.com/api/v1/dimension/admin/version?scalar_token=null 401 (Unauthorized)

And `journalctl -fu matrix-dimension` produces the following:

    Sep 10 14:46:18 MyServer matrix-dimension[28144]: Sep-10-2021 18:46:18.335 +00:00 verbose [DimensionStore [SQL]] Executing (default): SELECT "UserScalarToken"."id", "UserScalarToken"."userId", "UserScalarToken"."scalarToken", "UserScalarToken"."isDimensionToken", "UserScalarToken"."upstreamId", "user"."userId" AS "user.userId", "user"."isSelfBot" AS "user.isSelfBot" FROM "dimension_scalar_tokens" AS "UserScalarToken" LEFT OUTER JOIN "dimension_users" AS "user" ON "UserScalarToken"."userId" = "user"."userId" WHERE "UserScalarToken"."isDimensionToken" = true AND "UserScalarToken"."scalarToken" = 'null';
    Sep 10 14:46:18 MyServer matrix-dimension[28144]: Sep-10-2021 18:46:18.336 +00:00 error [ScalarService] Invalid token
    Sep 10 14:46:18 MyServer matrix-dimension[28144]: Error: Invalid token
    Sep 10 14:46:18 MyServer matrix-dimension[28144]:     at Function.<anonymous> (/home/node/matrix-dimension/build/app/db/ScalarStore.js:43:23)
    Sep 10 14:46:18 MyServer matrix-dimension[28144]:     at Generator.next (<anonymous>)
    Sep 10 14:46:18 MyServer matrix-dimension[28144]:     at fulfilled (/home/node/matrix-dimension/node_modules/tslib/tslib.js:107:62)
    Sep 10 14:46:18 MyServer matrix-dimension[28144]:     at runMicrotasks (<anonymous>)
    Sep 10 14:46:18 MyServer matrix-dimension[28144]:     at processTicksAndRejections (internal/process/task_queues.js:95:5)

For some reason it's being given a null token. Any idea what's wrong?

The dimension related settings in my vars.yml file are:

    matrix_dimension_enabled: true
    matrix_dimension_admins:
      - "@myuser:mydomain.com"
    matrix_dimension_access_token: "redacted"

I obtained the access token by creating a non-admin user named "dimension" and then following the directions for using CURL in "Setting up Dimension".

edit: Additionally, self-check reports no issues.

**Comment by aaronraimist** [comment]
If you haven't already you might want to ask in `#dimension:t2bot.io`

**Comment by PhoenixSheppy** [comment]
I can also reporting having this issue,

What information were you able to gather from `dimension:t2bot.io`?

**Comment by briankendall** [comment]
@PhoenixSheppy I haven't had a chance to ask them about it yet, but it's still on my to-do list.

**Comment by turbomettwurst** [comment]
Had the same issue, token was simply invalidated.
Login as the dimension user, get a fresh token and replace it.

**Comment by luixxiul** [comment]
Dimension was removed by https://github.com/spantaleev/matrix-docker-ansible-deploy/pull/4916.
