### ISSUE TITLE
Problem with registering in signal bridge

### ISSUE THREAD

**Issue by alkesander** [spantaleev/matrix-docker-ansible-deploy#1315]
Hi, can anyone help me understand what I'm doing wrong here? 

In bridge bot room I'm writing:
`register --captcha 03Axxx +48nnnnnnnnn`
the bot answers:
`Register SMS requested, please enter the code here.`
I'm receiving a SMS:
`<#> Twój kod weryfikacyjny SIGNAL to: 181215 doDiFGKPO1r`
and typing inside the room:
`181215`
This result in an error ([403] Authorization failed!)

See the whole error below:

```Unhandled error while handling command:
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/mautrix/bridge/commands/handler.py", line 406, in handle
    await self._run_handler(handler, evt)
  File "/usr/lib/python3.9/site-packages/mautrix_signal/commands/auth.py", line 126, in enter_register_code
    account = await evt.bridge.signal.verify(username, code=evt.args[0])
  File "/opt/mautrix-signal/mausignald/signald.py", line 108, in verify
    resp = await self.request_v1("verify", account=username, code=code)
  File "/opt/mautrix-signal/mausignald/rpc.py", line 223, in request_v1
    return await self.request(command, expected_response=command, version="v1", **data)
  File "/opt/mautrix-signal/mausignald/rpc.py", line 217, in request
    resp_type, resp_data = await self._raw_request(command, **data)
  File "/opt/mautrix-signal/mausignald/rpc.py", line 214, in _raw_request
    return await asyncio.shield(future)
mausignald.errors.AuthorizationFailedException: [403] Authorization failed!
```

Can you please help me understand what I'm doing wrong?

**Comment by Happyfeet01** [comment]
Have the same problems. Also get an error 403
