### ISSUE TITLE
DeprecationWarning: the imp module is deprecated in favour of importlib

### ISSUE THREAD

**Issue by jcalfee** [spantaleev/matrix-docker-ansible-deploy#1386]
Have I got the right python version?  This is debian 10 and Python 3.7.3.  

> $ ansible-playbook -i inventory/hosts setup.yml --tags=setup-all

```
...
TASK [matrix-base : Ensure Docker repository is enabled] ***********************************************************************************************************************************************************************************************
fatal: [matrix.DOMAIN.com]: FAILED! => changed=false 
  module_stderr: |-
    <stdin>:17: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
    Traceback (most recent call last):
      File "/tmp/ansible_apt_repository_payload_ewjwx8df/__main__.py", line 187, in __iter__
    StopIteration
  
    The above exception was the direct cause of the following exception:
  
    Traceback (most recent call last):
      File "<stdin>", line 113, in <module>
      File "<stdin>", line 105, in _ansiballz_main
      File "<stdin>", line 48, in invoke_module
      File "/usr/lib/python3.7/imp.py", line 234, in load_module
        return load_source(name, filename, file)
      File "/usr/lib/python3.7/imp.py", line 169, in load_source
        module = _exec(spec, sys.modules[name])
      File "<frozen importlib._bootstrap>", line 630, in _exec
      File "<frozen importlib._bootstrap_external>", line 728, in exec_module
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "/tmp/ansible_apt_repository_payload_ewjwx8df/__main__.py", line 550, in <module>
      File "/tmp/ansible_apt_repository_payload_ewjwx8df/__main__.py", line 518, in main
      File "/tmp/ansible_apt_repository_payload_ewjwx8df/__main__.py", line 436, in add_source
      File "/tmp/ansible_apt_repository_payload_ewjwx8df/__main__.py", line 349, in _add_valid_source
    RuntimeError: generator raised StopIteration
  module_stdout: ''
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
  rc: 1

PLAY RECAP *********************************************************************************************************************************************************************************************************************************************
matrix.DOMAIN.com    : ok=6    changed=2    unreachable=0    failed=1   

```

**Comment by aaronraimist** [comment]
You are probably using a fairly old version of Ansible. The playbook supports back to 2.7.1 so you should be fine but those version are quite old so you are likely to get deprecation warnings if you are still using them.

https://github.com/ansible/ansible/issues/56904#issuecomment-497025781

**Comment by aaronraimist** [comment]
You might be one of the only people using a version that old though. So maybe the support for those old versions has broken.

**Comment by jcalfee** [comment]
I should have included that.. I'm using `ansible-playbook 2.7.5`.  It is still unclear if the warning actually caused the failure. Great though, try with 2.9 now and then comment again.

**Comment by jcalfee** [comment]
Worth a try, I tend to docker everything that has not been in the Debian repositories for a while so that is a bit of security but extra work.  It is worth it though, I get a lot of freedom in containers without having to worry about the rest of my system so much, and once I have something dockerized it is basically ready to go on any new desktop or machine I need it one.

**Comment by jcalfee** [comment]
Version 2.9 got me past this error.  I got board and installed my own docker and gpg key so now that is causing a problem.  I can fix that up though.  Thanks!
