### ISSUE TITLE
SSL certificate verify failure during setup - MacOS >> Ubuntu 20.04

### ISSUE THREAD

**Issue by xthursdayx** [spantaleev/matrix-docker-ansible-deploy#1389]
I am trying to set up Matrix on my Ubuntu 20.04 VPS, running this playbook from my MacBook (MacOS 11.6), however I'm running into a problem when the playbook tries to download matrix-synapse-share-secret-auth. I am seeing the following error:
```
TASK [matrix-synapse : Download matrix-synapse-shared-secret-auth] *******************************************************************************************************************************
fatal: [matrix.my.domain]: FAILED! => changed=false
  dest: /matrix/synapse/ext/shared_secret_authenticator.py
  elapsed: 0
  msg: 'Request failed: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)>'
  url: https://raw.githubusercontent.com/devture/matrix-synapse-shared-secret-auth/1.0.2/shared_secret_authenticator.py
```
I tried to figure out what was causing this error, and tried a few things to fix it, including running the playbook with `ansible_python_interpreter: /usr/bin/python3` and setting `SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt` on the VPS and running `sudo update-ca-certificates`, but haven't been able to solve the issue. 

The version of ansible running on my MacBook is:
```
ansible [core 2.11.6]
  config file = /Users/xthursdayx/ansible/matrix-docker-ansible-deploy/ansible.cfg
  configured module search path = ['/Users/xthursdayx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/4.8.0/libexec/lib/python3.10/site-packages/ansible
  ansible collection location = /Users/xthursdayx/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.10.0 (default, Oct 13 2021, 06:45:00) [Clang 13.0.0 (clang-1300.0.29.3)]
  jinja version = 3.0.2
  libyaml = True
```
Do you have any ideas about what might be causing this problem? Thanks for the help!

My `vars.yml` is below:
```
# The bare domain name which represents your Matrix identity.
# Matrix user ids for your server will be of the form (`@user:<matrix-domain>`).
#
# Note: this playbook does not touch the server referenced here.
# Installation happens on another server ("matrix.<matrix-domain>").
#
# If you've deployed using the wrong domain, you'll have to run the Uninstalling step, 
# because you can't change the Domain after deployment.
#
# Example value: example.com
matrix_domain: my.domain

# This is something which is provided to Let's Encrypt when retrieving SSL certificates for domains.
#
# In case SSL renewal fails at some point, you'll also get an email notification there.
#
# If you decide to use another method for managing SSL certifites (different than the default Let's Encrypt),
# you won't be required to define this variable (see `docs/configuring-playbook-ssl-certificates.md`).
#
# Example value: someone@example.com
matrix_ssl_lets_encrypt_support_email: admin@my.domain

# A shared secret (between Coturn and Synapse) used for authentication.
# You can put any string here, but generating a strong one is preferred (e.g. `pwgen -s 64 1`).
matrix_coturn_turn_static_auth_secret: "**************************************************************"

# A secret used to protect access keys issued by the server.
# You can put any string here, but generating a strong one is preferred (e.g. `pwgen -s 64 1`).
matrix_synapse_macaroon_secret_key: "****************************************************************"

# A Postgres password to use for the superuser Postgres user (called `matrix` by default).
#
# The playbook creates additional Postgres users and databases (one for each enabled service)
# using this superuser account.
matrix_postgres_connection_password: "**************************************************************"

######################################################################
#
# matrix-base
#
######################################################################

matrix_well_known_matrix_server_enabled: true

matrix_ssl_retrieval_method: none

######################################################################
#
# /matrix-base
#
######################################################################



######################################################################
#
# matrix-client-element
#
######################################################################

matrix_client_element_container_http_host_bind_port: "127.0.0.1:8765"

# Use Dimension if enabled, otherwise fall back to Scalar
matrix_client_element_integrations_ui_url: "{{ matrix_dimension_integrations_ui_url if matrix_dimension_enabled else 'https://scalar.vector.im/' }}"
matrix_client_element_integrations_rest_url: "{{ matrix_dimension_integrations_rest_url if matrix_dimension_enabled else 'https://scalar.vector.im/api' }}"
matrix_client_element_integrations_widgets_urls: "{{ matrix_dimension_integrations_widgets_urls if matrix_dimension_enabled else ['https://scalar.vector.im/api'] }}"
matrix_client_element_integrations_jitsi_widget_url: "{{ matrix_dimension_integrations_jitsi_widget_url if matrix_dimension_enabled else 'https://scalar.vector.im/api/widgets/jitsi.html' }}"

matrix_client_element_jitsi_preferredDomain: "https://meet.my.domain"

matrix_client_element_registration_enabled: false

matrix_client_element_themes_enabled: true

######################################################################
#
# /matrix-client-element
#
######################################################################



######################################################################
#
# matrix-coturn
#
######################################################################

matrix_coturn_enabled: true

matrix_coturn_user_quota: 12 
matrix_coturn_total_quota: 1200

matrix_coturn_tls_enabled: true
matrix_coturn_tls_cert_path: "/data/ssl/fullchain.pem"
matrix_coturn_tls_key_path: "/data/ssl/privkey.pem"

matrix_coturn_container_additional_volumes:
 - src: "/matrix/ssl/config/live/my.domain/"
   dst: "/data/"
   options: ro   
   
######################################################################
#
# /matrix-coturn
#
######################################################################



######################################################################
#
# matrix-dimension
#
######################################################################

matrix_dimension_enabled: false

matrix_dimension_access_token: "********************************"

matrix_dimension_admins:
   - "@xthursdayx:{{ matrix_domain }}"
   - "@integration:{{ matrix_domain }}"

matrix_dimension_container_http_host_bind_port: "127.0.0.1:8184"

matrix_dimension_homeserver_federationUrl: "https://my.domain:8448"

matrix_dimension_configuration_extension_yaml: |
# Custom sticker pack options.
# Largely based on https://github.com/turt2live/matrix-sticker-manager
stickers:
  # Whether or not to allow people to add custom sticker packs
  enabled: true
  # The sticker manager bot to promote
  stickerBot: "@stickers:t2bot.io"
  # The sticker manager URL to promote
  managerUrl: "https://stickers.t2bot.io"

######################################################################
#
# /matrix-dimension
#
######################################################################



######################################################################
#
# matrix-etherpad
#
######################################################################

matrix_etherpad_enabled: true

######################################################################
#
# /matrix-etherpad
######################################################################



######################################################################
#
# matrix-jitsi
#
######################################################################

matrix_jitsi_enabled: true

matrix_jitsi_enable_auth: true
matrix_jitsi_enable_guests: true

# Run `bash inventory/scripts/jitsi-generate-passwords.sh` to generate these passwords,
# or define your own strong passwords manually.
matrix_jitsi_jicofo_component_secret: ********************************
matrix_jitsi_jicofo_auth_password: ********************************
matrix_jitsi_jvb_auth_password: ********************************
matrix_jitsi_jibri_recorder_password: ********************************
matrix_jitsi_jibri_xmpp_password: *******************************

# Controls whether Etherpad will be available within Jitsi
matrix_jitsi_etherpad_enabled: true

matrix_jitsi_web_container_http_host_bind_port: "127.0.0.1:13080"

######################################################################
#
# /matrix-jitsi
#
######################################################################



######################################################################
#
# matrix-ma1sd
#
######################################################################

# By default, this playbook installs the ma1sd identity server on the same domain as Synapse (`matrix_server_fqn_matrix`).
# If you wish to use the public identity servers (matrix.org, vector.im) instead of your own you may wish to disable this.
matrix_ma1sd_enabled: true

# Normally, matrix-nginx-proxy is enabled and nginx can reach ma1sd over the container network.
# If matrix-nginx-proxy is not enabled, or you otherwise have a need for it, you can expose
# ma1sd's web-server port.
matrix_ma1sd_container_http_host_bind_port: "127.0.0.1:8090"

matrix_ma1sd_configuration_extension_yaml: |
  register:
    policy:
      allowed: true
      threepid:
        email:
          domain:
            blacklist: ~
            whitelist: ~

######################################################################
#
# /matrix-ma1sd
#
######################################################################



######################################################################
#
# matrix-mailer
#
######################################################################

matrix_mailer_sender_address: "my@email.com"
matrix_mailer_relay_use: true
matrix_mailer_relay_host_name: "smtp.email.com"
matrix_mailer_relay_host_port: 587
matrix_mailer_relay_auth: true
matrix_mailer_relay_auth_username: "my@email.com"
matrix_mailer_relay_auth_password: "****************************"

######################################################################
#
# /matrix-mailer
#
######################################################################



######################################################################
#
# matrix-nginx-proxy
#
######################################################################

matrix_nginx_proxy_enabled: false

matrix_nginx_proxy_proxy_matrix_3pid_registration_enabled: true

######################################################################
#
# /matrix-nginx-proxy
#
######################################################################



######################################################################
#
# matrix-registration
#
######################################################################

matrix_registration_enabled: true

matrix_registration_admin_secret: "****************************************************************"

#matrix_registration_container_http_host_bind_port: "127.0.0.1:8767"
#
######################################################################
#
# /matrix-registration
######################################################################



######################################################################
#
# mautrix Signal
#
######################################################################

matrix_mautrix_signal_enabled: true

######################################################################
#
# /mautrix Signal
#
######################################################################



######################################################################
#
# matrix-synapse
#
######################################################################

matrix_synapse_workers_enabled: true
matrix_synapse_workers_preset: little-federation-helper

matrix_synapse_federation_enabled: true
matrix_synapse_container_federation_api_plain_host_bind_port: "127.0.0.1:8048"
matrix_synapse_container_federation_api_tls_host_bind_port: "127.0.0.1:8448"

matrix_synapse_tls_federation_listener_enabled: true
matrix_synapse_tls_certificate_path: "/data/fullchain.pem"
matrix_synapse_tls_private_key_path: "/data/privkey.pem"

matrix_synapse_enable_registration: false

matrix_synapse_registrations_require_3pid: ['email']

matrix_synapse_container_extra_arguments:
  - "--mount type=bind,src=/matrix/ssl/config/live/my.domainl/,dst=/data/,rw"
  
matrix_synapse_max_upload_size_mb: 500
matrix_synapse_tmp_directory_size_mb: 2048

matrix_synapse_ext_password_provider_shared_secret_auth_enabled: true
matrix_synapse_ext_password_provider_shared_secret_auth_shared_secret: "****************************************************************"

#matrix_synapse_ext_password_provider_rest_auth_enabled: true
#matrix_synapse_ext_password_provider_rest_auth_endpoint: "http://matrix-ma1sd:8090"
#
######################################################################
#
# /matrix-synapse
#
######################################################################



######################################################################
#
# matrix-synapse-admin
#
######################################################################

matrix_synapse_admin_enabled: true

#matrix_synapse_admin_container_http_host_bind_port: "127.0.0.1:8766"

######################################################################
#
# /matrix-synapse-admin
#
######################################################################
```

**Comment by aaronraimist** [comment]
Hmm. Does `curl https://raw.githubusercontent.com/devture/matrix-synapse-shared-secret-auth/1.0.2/shared_secret_authenticator.py` work on the server?

**Comment by xthursdayx** [comment]
Yep it does:
```
❯ curl https://raw.githubusercontent.com/devture/matrix-synapse-shared-secret-auth/1.0.2/shared_secret_authenticator.py
# -*- coding: utf-8 -*-
#
# Shared Secret Authenticator module for Matrix Synapse
# Copyright (C) 2018 Slavi Pantaleev
#
# http://devture.com/
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.

# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

import logging
import hashlib
import hmac
from twisted.internet import defer

logger = logging.getLogger(__name__)

class SharedSecretAuthenticator(object):

    def __init__(self, config, account_handler):
        self.account_handler = account_handler
        self.sharedSecret = config['sharedSecret']

    @defer.inlineCallbacks
    def check_password(self, user_id, password):
        # The password is supposed to be an HMAC of the user id, keyed with the shared secret.
        # It's not really a password in this case.
        given_hmac = password.encode('utf-8')

        logger.info('Authenticating user: %s', user_id)

        h = hmac.new(self.sharedSecret.encode('utf-8'), user_id.encode('utf-8'), hashlib.sha512)
        computed_hmac = h.hexdigest().encode('utf-8')

        try:
            is_identical = hmac.compare_digest(computed_hmac, given_hmac)
        except AttributeError:
            # `hmac.compare_digest` is only available on Python >= 2.7.7
            # Fall back to being somewhat insecure on older versions.
            is_identical = (computed_hmac == given_hmac)

        if not is_identical:
            logger.info('Bad hmac value for user: %s', user_id)
            defer.returnValue(False)
            return

        if not (yield self.account_handler.check_user_exists(user_id)):
            logger.info('Refusing to authenticate missing user: %s', user_id)
            defer.returnValue(False)
            return

        logger.info('Authenticated user: %s', user_id)
        defer.returnValue(True)

    @staticmethod
    def parse_config(config):
        if 'sharedSecret' not in config:
            raise Exception('Missing sharedSecret parameter for SharedSecretAuthenticator')
        return config
        ```

**Comment by xthursdayx** [comment]
For what it's worth, `curl https://raw.githubusercontent.com/devture/matrix-synapse-shared-secret-auth/1.0.2/shared_secret_authenticator.py` also works on my MacBook. Is it possible that the issue has to do with the Python version that Ansible (on my Mac) is using? Or is it only the Python version on the VPS that matters? I ask because when I run the command `ls -l $(which python3)` on my MacBook, I get the output `/usr/local/bin/python3 -> ../Cellar/python@3.9/3.9.7_1/bin/python3`, but when I run `ansible --verson` I see that ansible is running with this python module: `/usr/local/Cellar/ansible/4.8.0/libexec/lib/python3.10/site-packages/ansible`.  I'm not sure if that would matters though.

**Comment by aaronraimist** [comment]
> Is it possible that the issue has to do with the Python version that Ansible (on my Mac) is using? Or is it only the Python version on the VPS that matters?

I'm not really sure. I haven't seen anything like this before. My guess is that the issue is on the server.

> I ask because when I run the command ls -l $(which python3) on my MacBook, I get the output /usr/local/bin/python3 -> ../Cellar/python@3.9/3.9.7_1/bin/python3, but when I run ansible --verson I see that ansible is running with this python module: /usr/local/Cellar/ansible/4.8.0/libexec/lib/python3.10/site-packages/ansible. I'm not sure if that would matters though.

Mine looks the same so I don't think that is a problem.

**Comment by spantaleev** [comment]
The Python code that does the fetching runs on the server, yes. You may wish to try the `wget` command there.

**Comment by xthursdayx** [comment]
> The Python code that does the fetching runs on the server, yes. You may wish to try the `wget` command there.

Which `wget` command? Just run `wget https://raw.githubusercontent.com/devture/matrix-synapse-shared-secret-auth/1.0.2/shared_secret_authenticator.py` at `/matrix/synapse/ext/`?

**Comment by spantaleev** [comment]
I meant the `curl` command provided by @aaronraimist above, not `wget`. Sorry for the confusion.

**Comment by aaronraimist** [comment]
They did run it on the server initially and it worked. I'm not sure why curl would be okay with the certificate but python wouldn't be. Maybe you could use https://superuser.com/a/1026746 to get more info from curl about what it thinks the status of the certificate is https://superuser.com/a/1026746.

**Comment by aaronraimist** [comment]
Or maybe `pip install --upgrade certifi` would help

**Comment by xthursdayx** [comment]
Thanks @aaronraimist I ran `curl --insecure -vvI https://raw.githubusercontent.com/devture/matrix-synapse-shared-secret-auth/1.0.2/shared_secret_authenticator.py 2>&1 | awk 'BEGIN { cert=0 } /^\* Server certificate:/ { cert=1 } /^\*/ { if (cert) print }'` and got the following output:
```
* Server certificate:
*  subject: C=US; ST=California; L=San Francisco; O=GitHub, Inc.; CN=www.github.com
*  start date: May  6 00:00:00 2020 GMT
*  expire date: Apr 14 12:00:00 2022 GMT
*  issuer: C=US; O=DigiCert Inc; OU=www.digicert.com; CN=DigiCert SHA2 High Assurance Server CA
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x55b0d6d5aec0)
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* Connection state changed (MAX_CONCURRENT_STREAMS == 100)!
* Connection #0 to host raw.githubusercontent.com left intact
```

I also tried `pip install --upgrade certifi`, but got:
```
Requirement already up-to-date: certifi in /usr/local/lib/python3.8/dist-packages (2021.10.8)
```

However the problem still remains when I run the playbook.

**Comment by aaronraimist** [comment]
Googling around I see someone say do `brew reinstall openssl`. Other people say ansible installed from brew doesn't work and installing ansible from pip worked for them. If neither of those work then it seems it must be an Ansible bug (or possibly Python).

**Comment by xthursdayx** [comment]
Thanks for putting in some more effort to help figure this out @aaronraimist. I've also looked around online, but haven't figured out the problem yet. I'll list the things I've tried here though, just to document the issue. 

I tried reinstalling opensll via homebrew but received the following caveats:
```
==> Caveats
A CA file has been bootstrapped using certificates from the system
keychain. To add additional certificates, place .pem files in
  /usr/local/etc/openssl@3/certs

and run
  /usr/local/opt/openssl@3/bin/c_rehash

openssl@3 is keg-only, which means it was not symlinked into /usr/local,
because macOS provides LibreSSL.

If you need to have openssl@3 first in your PATH, run:
  echo 'export PATH="/usr/local/opt/openssl@3/bin:$PATH"' >> ~/.zshrc

For compilers to find openssl@3 you may need to set:
  export LDFLAGS="-L/usr/local/opt/openssl@3/lib"
  export CPPFLAGS="-I/usr/local/opt/openssl@3/include"

For pkg-config to find openssl@3 you may need to set:
  export PKG_CONFIG_PATH="/usr/local/opt/openssl@3/lib/pkgconfig"
```
This makes me wonder if the issue is linked to LibreSSL somehow...? `/usr/local/opt/openssl@3/bin` is already in my PATH, so the only other thing I thought to try was to make sure the ca-cert was being read. Because the command `python3 -m certifi` gave me the ca file `/usr/local/lib/python3.9/site-packages/certifi/cacert.pem`, I tried symlinking this file into `/usr/local/etc/openssl@3/certs` and running `/usr/local/opt/openssl@3/bin/c_rehash', but still ended up with the same error when running the playbook.

I also tried adding the following variables to my rc file (.zshrc in my case):
```
export CERT_PATH=$(python3 -m certifi)
export SSL_CERT_FILE=${CERT_PATH}
export REQUESTS_CA_BUNDLE=${CERT_PATH}
```
This also didn't make any difference. 

Finally, I uninstalled the homebrew installation of ansible and reinstalled ansible using `python -m pip install --user ansible`. The next time I tried to run the playbook it produced an error related to installing Postgres which told me to install the passlib python module on my MacBook, which I did. After re-running the playbook I am once again back to the SSL certificate verify failure.

**Comment by spantaleev** [comment]
Seems like you're focusing a lot on the MacOS side of things and not on the server. I suspect that the problem is somewhere on the server though.

A good way to rule out your local MacOS installation of Ansible (and related software) is to try running the playbook somewhere else. You can try putting the playbook on the Ubuntu server itself and adjust the `inventory/hosts` file to use `ansible_connection=local`. If you have another server, you could also run it there. You could also run the playbook from a Docker container on your MacOS machine or some other server (see `docs/ansible.md`).

-------

Unrelated to the above experiment, you could try running the `ansible-playbook` command with a `-vvvv` flag and see if you get some more helpful debugging output.

**Comment by xthursdayx** [comment]
Thanks for the suggestions @spantaleev. I tried running the playbook from the Ubuntu VPS using `ansible_connection=local` and ended up with the same error, so it seems you're right about the problem being with the server rather than my Mac. 

I reran the playbook with the `-vvvv` flag and got this output for the SSL certificate verify failure:
```
TASK [matrix-synapse : Download matrix-synapse-shared-secret-auth] *********************************************************************************************************************************************
task path: /usr/local/docker/matrix-docker-ansible-deploy/roles/matrix-synapse/tasks/ext/shared-secret-auth/setup_install.yml:8
Using module file /usr/lib/python3/dist-packages/ansible/modules/get_url.py
Pipelining is enabled.
<SERVER.IP> ESTABLISH LOCAL CONNECTION FOR USER: xthursdayx
<SERVER.IP> EXEC /bin/sh -c 'sudo -H -S  -p "[sudo via ansible, key=********************************] password:" -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-********************************** ; /usr/bin/python3'"'"' && sleep 0'
fatal: [matrix.my.domain]: FAILED! => changed=false
  dest: /matrix/synapse/ext/shared_secret_authenticator.py
  elapsed: 0
  invocation:
    module_args:
      attributes: null
      backup: false
      checksum: ''
      client_cert: null
      client_key: null
      dest: /matrix/synapse/ext/shared_secret_authenticator.py
      force: true
      force_basic_auth: false
      group: matrix
      headers: null
      http_agent: ansible-httpget
      mode: 288
      owner: matrix
      selevel: null
      serole: null
      setype: null
      seuser: null
      sha256sum: ''
      timeout: 10
      tmp_dest: null
      unsafe_writes: false
      url: https://raw.githubusercontent.com/devture/matrix-synapse-shared-secret-auth/1.0.2/shared_secret_authenticator.py
      url_password: null
      url_username: null
      use_gssapi: false
      use_proxy: true
      validate_certs: true
  msg: 'Request failed: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)>'
  url: https://raw.githubusercontent.com/devture/matrix-synapse-shared-secret-auth/1.0.2/shared_secret_authenticator.py
```

**Comment by spantaleev** [comment]
Is `ca-certificates` installed on the server (`apt search ca-certificates` should say `[installed]` or something like that)?

**Comment by xthursdayx** [comment]
This is the output I received:
```
ca-certificates/focal-updates,focal-security,focal-updates,focal-security,now 20210119~20.04.2 all [installed]
  Common CA certificates

ca-certificates-java/focal,focal 20190405ubuntu1 all
  Common CA certificates (JKS keystore)

ca-certificates-mono/focal,focal 6.8.0.105+dfsg-2 all
  Common CA certificates (Mono keystore)

liblwp-protocol-https-perl/focal,focal 6.07-2ubuntu2 all
  HTTPS driver for LWP::UserAgent
```

**Comment by spantaleev** [comment]
This seems good.

What happens if you launch `python` (or `python3`) on your server and paste the following lines of code there:

```python
import urllib.request
url = 'https://raw.githubusercontent.com/devture/matrix-synapse-shared-secret-auth/1.0.2/shared_secret_authenticator.py'
f = urllib.request.urlopen(url)
print(f.read().decode('utf-8'))
```

**Comment by xthursdayx** [comment]
This seems to be the root of the problem. I got this output after the third line of code:
```
>>> import urllib.request
>>> url = 'https://raw.githubusercontent.com/devture/matrix-synapse-shared-secret-auth/1.0.2/shared_secret_authenticator.py'
>>> f = urllib.request.urlopen(url)
Traceback (most recent call last):
  File "/usr/lib/python3.8/urllib/request.py", line 1354, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/lib/python3.8/http/client.py", line 1252, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1298, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1247, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1007, in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 947, in send
    self.connect()
  File "/usr/lib/python3.8/http/client.py", line 1421, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 1397, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/usr/lib/python3.8/urllib/request.py", line 1357, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)>
```
Then:
```
>>> print(f.read().decode('utf-8'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'f' is not defined
>>>
```

**Comment by spantaleev** [comment]
So it seems like your problem is with the Python installation on the server.

What does `echo 'import certifi; print(certifi.__version__);' | python3` say?

I'm not really sure how Python does SSL communication. Seems like one way is with the help of the [certifi](https://pypi.org/project/certifi/) Python package. Another way may be to use the upstream CA bundle provided by the `ca-certificates` Ubuntu package. If you have `certifi` installed, that package probably takes priority. If it's outdated, it may lead to a problem.

On my Ubuntu 20.04 server, the above command prints `2019.11.28`, which while outdated (the newest seems to be `2021.10.8`), I have no problems with SSL communication from Python.

The `certifi` Python package on my server seems to be installed from the Ubuntu repositories via a `python3-certifi` package. Try `apt search python3-certifi` on your server. On mine, I get:

```
python3-certifi/focal,now 2019.11.28-1 all [installed,automatic]
```

**Comment by xthursdayx** [comment]
Sorry for the delay, was out of town for work. 

The result of `echo 'import certifi; print(certifi.__version__);' | python3` is: `2021.10.08`, so seemingly the most up-to-date version.

When I searched for `python3-certifi` I got the result: `python3-certifi/focal,focal,now 2019.11.28-1 all [installed,automatic]` which seems correct...

**Comment by spantaleev** [comment]
Maybe you did some manual `pip` installation or something, which force-upgraded `certifi`. Perhaps it's not fully installed or something and now it doesn't work.

You should probably find a way to remove it and reinstall `python3-certifi` cleanly. Perhaps by `pip`-removing the existing `certifi` package. Perhaps by force-reinstalling `python3-certifi` (maybe `apt reinstall python3-certifi`).

**Comment by xthursdayx** [comment]
I tried to reinstall `python3-certifi` as well as `ca-certificates` and `openssl`, but I still get the same playbook error when I run the playbook from the VPS. At this point I don't really know what else I can change...

**Comment by spantaleev** [comment]
Now that you've done all that, did the result of `echo 'import certifi; print(certifi.__version__);' | python3` change?

You should probably focus on this and on getting these basic Python tests working. The problem is not in the playbook. You can also look for help elsewhere (Ubuntu support channels / chats, Python support channels / chats, etc).

Of course, please do keep us posted with whatever you can find!

**Comment by xthursdayx** [comment]
The result of `echo 'import certifi; print(certifi.__version__);' | python3` is still `2021.10.08`, but I think that's because it's the most recent version. 

I'll guess look elsewhere for help and report back if I figure anything out.

**Comment by spantaleev** [comment]
I think it should not be such a recent version.

The `python3-certifi` package supposedly installs the `2019.11.08` version. If that's what installed and the script says `2021.10.08`, then something is overwriting whatever the package installed. It might be the reason why certifi is not actually working. You have 2 versions installed on top of one another.
