### ISSUE TITLE
Unable to deploy with synapse-admin

### ISSUE THREAD

**Issue by lemmy04** [spantaleev/matrix-docker-ansible-deploy#1462]
I'm deploying on a VM on the oracle cloud, and I can't deploy with synapse-admin enabled:

```
TASK [Ensure matrix-synapse-admin Docker image is built] *************************************************************************************************
fatal: [matrix.eregion.de]: FAILED! => changed=false 
  msg: 'Error building localhost/awesometechnologies/synapse-admin - code: 1, message: The command ''/bin/sh -c yarn build'' returned a non-zero code: 1, logs: [''Step 1/8 : FROM node:current as builder'', ''\n'', '' ---> f62205fa0df4\n'', ''Step 2/8 : WORKDIR /src'', ''\n'', '' ---> Running in c654ce2afc2c\n'', ''Removing intermediate container c654ce2afc2c\n'', '' ---> 9cd2c1b78c7a\n'', ''Step 3/8 : COPY . /src'', ''\n'', '' ---> 0ee0cfc0a477\n'', ''Step 4/8 : RUN yarn --network-timeout=100000 install'', ''\n'', '' ---> Running in 9cd0f35b886f\n'', ''yarn install v1.22.15\n'', ''[1/4] Resolving packages...\n'', ''[2/4] Fetching packages...\n'', ''info fsevents@2.3.2: The platform "linux" is incompatible with this module.\n'', ''info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.\n'', ''info fsevents@1.2.13: The platform "linux" is incompatible with this module.\ninfo "fsevents@1.2.13" is an optional dependency and failed compatibility
    check. Excluding it from installation.\n'', ''[3/4] Linking dependencies...\n'', ''\x1b[91mwarning "react-admin > connected-react-router@6.9.1" has unmet peer dependency "history@^4.7.2".\n\x1b[0m'', ''\x1b[91mwarning "react-scripts > @typescript-eslint/eslint-plugin > tsutils@3.21.0" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta".\n\x1b[0m'', ''\x1b[91mwarning " > @testing-library/user-event@13.1.8" has unmet peer dependency "@testing-library/dom@>=7.21.4".\n\x1b[0m'', ''\x1b[91mwarning " > ra-test@3.15.0" has unmet peer dependency "ra-core@^3.13.0".\n\x1b[0m'', ''\x1b[91mwarning " > ra-test@3.15.0" has unmet peer dependency "react-redux@^7.1.0".\n\x1b[0m'', ''\x1b[91mwarning " > ra-test@3.15.0" has unmet peer dependency "react-router@^5.1.0".\nwarning " > ra-test@3.15.0" has unmet peer dependency "react-router-dom@^5.1.0".\n\x1b[0m'', ''\x1b[91mwarning " >
    ra-test@3.15.0" has unmet peer dependency "redux@^3.7.2 || ^4.0.3".\n\x1b[0m'', ''[4/4] Building fresh packages...\n'', ''Done in 58.53s.\n'', ''Removing intermediate container 9cd0f35b886f\n'', '' ---> d972b6fabae0\n'', ''Step 5/8 : RUN yarn build'', ''\n'', '' ---> Running in d8936d6048f2\n'', ''yarn run v1.22.15\n'', ''$ REACT_APP_VERSION=$(git describe --tags) react-scripts build\n'', ''Creating an optimized production build...\n'', ''\x1b[91mError: error:0308010C:digital envelope routines::unsupported\n    at new Hash (node:internal/crypto/hash:67:19)\n    at Object.createHash (node:crypto:130:10)\n    at module.exports (/src/node_modules/webpack/lib/util/createHash.js:135:53)\n    at NormalModule._initBuildHash (/src/node_modules/webpack/lib/NormalModule.js:417:16)\n    at handleParseError (/src/node_modules/webpack/lib/NormalModule.js:471:10)\n    at /src/node_modules/webpack/lib/NormalModule.js:503:5\n    at /src/node_modules/webpack/lib/NormalModule.js:358:12\n    at /src/node_modules/loader-runner/lib/LoaderRunner.js:373:3\n    at
    iterateNormalLoaders (/src/node_modules/loader-runner/lib/LoaderRunner.js:214:10)\n    at iterateNormalLoaders (/src/node_modules/loader-runner/lib/LoaderRunner.js:221:10)\n    at /src/node_modules/loader-runner/lib/LoaderRunner.js:236:3\n    at runSyncOrAsync (/src/node_modules/loader-runner/lib/LoaderRunner.js:130:11)\n    at iterateNormalLoaders (/src/node_modules/loader-runner/lib/LoaderRunner.js:232:2)\n    at Array.<anonymous> (/src/node_modules/loader-runner/lib/LoaderRunner.js:205:4)\n    at Storage.finished (/src/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)\n    at /src/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9\n\x1b[0m'', "\x1b[91m/src/node_modules/react-scripts/scripts/build.js:19\n  throw err;\n  ^\n\nError: error:0308010C:digital envelope routines::unsupported\n    at new Hash (node:internal/crypto/hash:67:19)\n    at Object.createHash (node:crypto:130:10)\n    at module.exports (/src/node_modules/webpack/lib/util/createHash.js:135:53)\n    at
    NormalModule._initBuildHash (/src/node_modules/webpack/lib/NormalModule.js:417:16)\n    at /src/node_modules/webpack/lib/NormalModule.js:452:10\n    at /src/node_modules/webpack/lib/NormalModule.js:323:13\n    at /src/node_modules/loader-runner/lib/LoaderRunner.js:367:11\n    at /src/node_modules/loader-runner/lib/LoaderRunner.js:233:18\n    at context.callback (/src/node_modules/loader-runner/lib/LoaderRunner.js:111:13)\n    at /src/node_modules/react-scripts/node_modules/babel-loader/lib/index.js:59:103 {\n  opensslErrorStack: [ ''error:03000086:digital envelope routines::initialization error'' ],\n  library: ''digital envelope routines'',\n  reason: ''unsupported'',\n  code: ''ERR_OSSL_EVP_UNSUPPORTED''\n}\n\x1b[0m", ''\x1b[91m\nNode.js v17.2.0\n\x1b[0m'', ''\x1b[91merror Command failed with exit code 1.\n\x1b[0m'', ''info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.\n'', ''Removing intermediate container d8936d6048f2\n'']'
```

Is this an architecture thing? the VM is aarch64, of that "always free" tier on the oracle cloud.

**Comment by lemmy04** [comment]
yep, arm64 (even though the kernel calls it aarch64)

**Comment by aaronraimist** [comment]
Self building the stable version of Synapse Admin is currently broken due to https://github.com/webpack/webpack/issues/14532. I submitted a PR to work around that issue (https://github.com/Awesome-Technologies/synapse-admin/pull/205) however they haven't released a new version yet with that patch included. For now you can add

```
matrix_synapse_admin_container_self_build: true
matrix_synapse_admin_version: master
```

to your `vars.yml` to build the master branch which includes that patch and should build properly.

**Comment by lemmy04** [comment]
that worked, I have the admin frontend now.
