### ISSUE TITLE
matrix-registration does not start

### ISSUE THREAD

**Issue by lemmy04** [spantaleev/matrix-docker-ansible-deploy#1463]
I'm deploying on an oracle cloud free instance, and the matrix-registration service isn't starting.

journalctl -ex shows python errors:

```
Dec 15 11:39:10 matrix.eregion.de matrix-registration[172420]: Traceback (most recent call last):
Dec 15 11:39:10 matrix.eregion.de matrix-registration[172420]:   File "/usr/local/bin/matrix-registration", line 5, in <module>
Dec 15 11:39:10 matrix.eregion.de matrix-registration[172420]:     from matrix_registration.app import cli
Dec 15 11:39:10 matrix.eregion.de matrix-registration[172420]:   File "/usr/local/lib/python3.8/site-packages/matrix_registration/app.py", line 9, in <mo>
Dec 15 11:39:10 matrix.eregion.de matrix-registration[172420]:     from flask_limiter.util import get_ipaddr
Dec 15 11:39:10 matrix.eregion.de matrix-registration[172420]: ImportError: cannot import name 'get_ipaddr' from 'flask_limiter.util' (/usr/local/lib/pyt>
```

**Comment by spantaleev** [comment]
Oracle instance likely means `arm64`.

On `arm64`, self-building is enabled for `matrix-registration`.

Unless you've redefined `matrix_registration_container_image_self_build_branch`, we should be pulling and building the `v0.7.2` branch of `matrix-registration`.

It seems like its [Dockerfile](https://github.com/ZerataX/matrix-registration/blob/v0.7.2/Dockerfile) fixes some Python / Alpine versions, so what you've built should be similar to what they built and pushed to Docker Hub. Unless `pip install` does something different with regards to the `Flask` version, etc., defined in [setup.py](https://github.com/ZerataX/matrix-registration/blob/v0.7.2/setup.py)

**Comment by lemmy04** [comment]
```
lemmy@mio:~/Work/matrix.eregion.de/matrix-docker-ansible-deploy> grep registr inventory/host_vars/matrix.eregion.de/vars.yml 
matrix_registration_enabled: false
matrix_registration_admin_secret: "..."
```

that's all I have in my vars file in regard to the registration bits...

**Comment by rpush-01** [comment]
i believe this is due to new versions of flask-limiter having deprecated get_ipaddr, although that should result in matrix-registration breaking on all platforms, not just arm64

**Comment by spantaleev** [comment]
It probably results in it breaking on all platforms if you self-build it. For `amd64` there's a pre-built image, so most users do not go through self-building, unless they explicitly enable it.

**Comment by vinogradovnet** [comment]
To resolve this issue I created https://github.com/vinogradovnet/matrix-registration

In this repo original matrix-registration v0.7.2 with only one change in setup.py

        "flask-limiter==2.0.0"

and than you need to change in your matrix-docker-ansible-deploy/roles/matrix-registration/defaults

matrix_registration_container_image_self_build_repo: "https://github.com/vinogradovnet/matrix-registration.git"

this way I resolve my problem with installation on Oracle cloud

**Comment by lemmy04** [comment]
even with that, still the same:
```Jan 19 20:40:05 matrix.eregion.de systemd[1]: Starting matrix-registration...
Jan 19 20:40:05 matrix.eregion.de systemd[1]: Started matrix-registration.
Jan 19 20:40:06 matrix.eregion.de matrix-registration[182903]: Traceback (most recent call last):
Jan 19 20:40:06 matrix.eregion.de matrix-registration[182903]:   File "/usr/local/bin/matrix-registration", line 5, in <module>
Jan 19 20:40:06 matrix.eregion.de matrix-registration[182903]:     from matrix_registration.app import cli
Jan 19 20:40:06 matrix.eregion.de matrix-registration[182903]:   File "/usr/local/lib/python3.8/site-packages/matrix_registration/app.py", line 9, in <module>
Jan 19 20:40:06 matrix.eregion.de matrix-registration[182903]:     from flask_limiter.util import get_ipaddr
Jan 19 20:40:06 matrix.eregion.de matrix-registration[182903]: ImportError: cannot import name 'get_ipaddr' from 'flask_limiter.util' (/usr/local/lib/python3.8/site-packages/flask_limiter/util.py)
Jan 19 20:40:07 matrix.eregion.de systemd[1]: matrix-registration.service: Main process exited, code=exited, status=1/FAILURE
Jan 19 20:40:07 matrix.eregion.de systemd[1]: matrix-registration.service: Failed with result 'exit-code'.
```

**Comment by vinogradovnet** [comment]
Do you have 
`matrix_registration_container_image_self_build: true`

in yours `vars.yml`?

**Comment by lemmy04** [comment]
yep.

**Comment by lemmy04** [comment]
> Oracle instance likely means `arm64`.
> 
> On `arm64`, self-building is enabled for `matrix-registration`.
> 
> Unless you've redefined `matrix_registration_container_image_self_build_branch`, we should be pulling and building the `v0.7.2` branch of `matrix-registration`.
> 
> It seems like its [Dockerfile](https://github.com/ZerataX/matrix-registration/blob/v0.7.2/Dockerfile) fixes some Python / Alpine versions, so what you've built should be similar to what they built and pushed to Docker Hub. Unless `pip install` does something different with regards to the `Flask` version, etc., defined in [setup.py](https://github.com/ZerataX/matrix-registration/blob/v0.7.2/setup.py)

...there is no v0.7.2 branch...

**Comment by PeesFoor** [comment]
> > Oracle instance likely means `arm64`.
> > On `arm64`, self-building is enabled for `matrix-registration`.
> > Unless you've redefined `matrix_registration_container_image_self_build_branch`, we should be pulling and building the `v0.7.2` branch of `matrix-registration`.
> > It seems like its [Dockerfile](https://github.com/ZerataX/matrix-registration/blob/v0.7.2/Dockerfile) fixes some Python / Alpine versions, so what you've built should be similar to what they built and pushed to Docker Hub. Unless `pip install` does something different with regards to the `Flask` version, etc., defined in [setup.py](https://github.com/ZerataX/matrix-registration/blob/v0.7.2/setup.py)
> 
> ...there is no v0.7.2 branch...

I had the same problem

You need to set 
`matrix_registration_version: "latest"`
and 
`matrix_registration_container_image_self_build_repo: "https://github.com/vinogradovnet/matrix-registration.git"`

in the file matrix-docker-ansible-deploy/roles/matrix-registration/defaults/main.yml

as the repo @vinogradovnet setup has no version other than the master

**Comment by lemmy04** [comment]
> You need to set `matrix_registration_version: "latest"` and `matrix_registration_container_image_self_build_repo: "https://github.com/vinogradovnet/matrix-registration.git"`
> 
> in the file matrix-docker-ansible-deploy/roles/matrix-registration/defaults/main.yml
> 
> as the repo @vinogradovnet setup has no version other than the master

that worked.

**Comment by mooks42** [comment]
> > > Oracle instance likely means `arm64`.
> > > On `arm64`, self-building is enabled for `matrix-registration`.
> > > Unless you've redefined `matrix_registration_container_image_self_build_branch`, we should be pulling and building the `v0.7.2` branch of `matrix-registration`.
> > > It seems like its [Dockerfile](https://github.com/ZerataX/matrix-registration/blob/v0.7.2/Dockerfile) fixes some Python / Alpine versions, so what you've built should be similar to what they built and pushed to Docker Hub. Unless `pip install` does something different with regards to the `Flask` version, etc., defined in [setup.py](https://github.com/ZerataX/matrix-registration/blob/v0.7.2/setup.py)
> > 
> > 
> > ...there is no v0.7.2 branch...
> 
> I had the same problem
> 
> You need to set `matrix_registration_version: "latest"` and `matrix_registration_container_image_self_build_repo: "https://github.com/vinogradovnet/matrix-registration.git"`
> 
> in the file matrix-docker-ansible-deploy/roles/matrix-registration/defaults/main.yml
> 
> as the repo @vinogradovnet setup has no version other than the master

Thank you! Fixed the problem :)

**Comment by Jesse-Millwood** [comment]
I ran into this issue as well. 

These are the changes I made, which seem to be in line with what was suggested here: 

```
diff --git a/roles/matrix-registration/defaults/main.yml b/roles/matrix-registration/defaults/main.yml
index d924551a..bbfc6103 100644
--- a/roles/matrix-registration/defaults/main.yml
+++ b/roles/matrix-registration/defaults/main.yml
@@ -4,8 +4,8 @@

 matrix_registration_enabled: true

-matrix_registration_container_image_self_build: false
-matrix_registration_container_image_self_build_repo: "https://github.com/ZerataX/matrix-registration"
+matrix_registration_container_image_self_build: true
+matrix_registration_container_image_self_build_repo: "https://github.com/vinogradovnet/matrix-registration.git"
 matrix_registration_container_image_self_build_branch: "{{ 'master' if matrix_registration_version == 'latest' else matrix_registration_version }}"

 matrix_registration_base_path: "{{ matrix_base_data_path }}/matrix-registration"
@@ -13,7 +13,7 @@ matrix_registration_config_path: "{{ matrix_registration_base_path }}/config"
 matrix_registration_data_path: "{{ matrix_registration_base_path }}/data"
 matrix_registration_docker_src_files_path: "{{ matrix_registration_base_path }}/docker-src"

-matrix_registration_version: "v0.7.2"
+matrix_registration_version: "latest"

 matrix_registration_docker_image: "{{ matrix_registration_docker_image_name_prefix }}zeratax/matrix-registration:{{ matrix_registration_version }}"
 matrix_registration_docker_image_name_prefix: "{{ 'localhost/' if matrix_registration_container_image_self_build else matrix_container_global_registry_prefix }}"
```

However, then I got an issue with markup safe, which is the same as here: https://github.com/pallets/markupsafe/issues/284#issuecomment-1044168203

So I pinned it to a version with: `sudo pip3 install markupsafe==2.0.1` 

Then I got an issue with not being able to access github: 
```
TASK [matrix-coturn : Ensure Coturn image is pulled] ***************************************************************************************************************************************
skipping: [matrix.chat.mellowmoonling.space]

TASK [matrix-coturn : Ensure Coturn repository is present on self-build] *******************************************************************************************************************
fatal: [matrix.chat.mellowmoonling.space]: FAILED! => changed=false 
  cmd: /usr/bin/git ls-remote origin -h refs/heads/docker/4.5.2-r8
  msg: 'fatal: unable to access ''https://github.com/coturn/coturn/'': Failed to connect to github.com port 443: Connection timed out'
  rc: 128
  stderr: |-
    fatal: unable to access 'https://github.com/coturn/coturn/': Failed to connect to github.com port 443: Connection timed out
  stderr_lines: <omitted>
  stdout: ''
  stdout_lines: <omitted>
```

I can git clone that repository from the command line so I'm wondering if it is a docker or docker network thing. I am also on an oracle arm64 vps. I haven't blown away the iptables as this https://matrix.org/docs/guides/free-small-matrix-server suggests because I did that before and could not get the ports to be open. 
Has anyone else ran into this or have an idea to test out some connectivity issues? 
(for what it's worth dealing with network stuff is new to me as is ansible)

**Comment by mooks42** [comment]
well it fixed the problem only once it seems, now it is not starting again.
`Apr 14 22:10:43 matrix systemd[1]: Started matrix-registration.
Apr 14 22:10:44 matrix matrix-registration[2366137]: Traceback (most recent call last):
Apr 14 22:10:44 matrix matrix-registration[2366137]:   File "/usr/local/bin/matrix-registration", line 5, in <module>
Apr 14 22:10:44 matrix matrix-registration[2366137]:     from matrix_registration.app import cli
Apr 14 22:10:44 matrix matrix-registration[2366137]:   File "/usr/local/lib/python3.8/site-packages/matrix_registration/__init__.py", line 1, in <module>
Apr 14 22:10:44 matrix matrix-registration[2366137]:     from . import api
Apr 14 22:10:44 matrix matrix-registration[2366137]:   File "/usr/local/lib/python3.8/site-packages/matrix_registration/api.py", line 9, in <module>
Apr 14 22:10:44 matrix matrix-registration[2366137]:     from flask import (
Apr 14 22:10:44 matrix matrix-registration[2366137]:   File "/usr/local/lib/python3.8/site-packages/flask/__init__.py", line 14, in <module>
Apr 14 22:10:44 matrix matrix-registration[2366137]:     from jinja2 import escape
Apr 14 22:10:44 matrix matrix-registration[2366137]:   File "/usr/local/lib/python3.8/site-packages/jinja2/__init__.py", line 12, in <module>
Apr 14 22:10:44 matrix matrix-registration[2366137]:     from .environment import Environment
Apr 14 22:10:44 matrix matrix-registration[2366137]:   File "/usr/local/lib/python3.8/site-packages/jinja2/environment.py", line 25, in <module>
Apr 14 22:10:44 matrix matrix-registration[2366137]:     from .defaults import BLOCK_END_STRING
Apr 14 22:10:44 matrix matrix-registration[2366137]:   File "/usr/local/lib/python3.8/site-packages/jinja2/defaults.py", line 3, in <module>
Apr 14 22:10:44 matrix matrix-registration[2366137]:     from .filters import FILTERS as DEFAULT_FILTERS  # noqa: F401
Apr 14 22:10:44 matrix matrix-registration[2366137]:   File "/usr/local/lib/python3.8/site-packages/jinja2/filters.py", line 13, in <module>
Apr 14 22:10:44 matrix matrix-registration[2366137]:     from markupsafe import soft_unicode
Apr 14 22:10:44 matrix matrix-registration[2366137]: ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/usr/local/lib/python3.8/site-packages/markupsafe/__init__.py)
Apr 14 22:10:44 matrix systemd[1]: matrix-registration.service: Main process exited, code=exited, status=1/FAILURE
`

**Comment by CreeperFace00** [comment]
After adding
 `matrix_registration_version: "latest"
matrix_registration_container_image_self_build_repo: "https://github.com/Jesse-Millwood/matrix-registration.git"`
to my vars.yml file, matrix-registration is compiling and starting without errors.

**Comment by paboum** [comment]
Can't you just submit a PR to upstream? It's not that everyone wants to or needs to use your playbook.

**Comment by spantaleev** [comment]
Because `matrix-registration` is an unmaintained project which hasn't had a proper release in a long time.

I actually wanted us to keep it up to date, but they [broke their Docker image](https://github.com/zeratax/matrix-registration/issues/created_by/spantaleev) while chasing some hipster `docker` + `nix` stuff.. So even if this gets fixed upstream, it will be part of some `master` / `latest` build, which doesn't work.. We're stuck on the nicely-working old `0.9.1` version, which we need to patch-up a bit to make it build.. Well, they may backport the patch and release `0.9.2`, but.. I don't think they care to do that, judging by their lack of releases or effort spent on fixing the Docker image.

**Comment by paboum** [comment]
It seems you're right, I found more issues and tried to contribute to their bug report githup page and only got locked out. Apparently, it should be forked and taken over by somewhone who has interest in developing the project. I'm not that person, will simply use some of the alternatives.
