### ISSUE TITLE
SQLite import problem

### ISSUE THREAD

**Issue by DUCKCHI** [spantaleev/matrix-docker-ansible-deploy#1597]
Previously, synapse was used to matrix.example.com, but the domain was changed to example.com as it changed to playbook.

Attempting to migrate the existing Sqlite database of matrix.example.com to the playbook results in the following errors.
In homeserver.db, 'matrix' is set as the owner. Also, the o+w authority is set.

`TASK [matrix-postgres : Wait a bit, so that Postgres can start] ****************
ok: [matrix.example.com -> 127.0.0.1]

TASK [matrix-postgres : Import SQLite database into Postgres] ******************
fatal: [matrix.example.com]: FAILED! => changed=true
  cmd:
  - docker
  - run
  - --rm
  - --name=matrix-synapse-migrate
  - --log-driver=none
  - --user=997:1002
  - --cap-drop=ALL
  - --network=matrix
  - --entrypoint=python
  - --mount
  - type=bind,src=/matrix/synapse/config,dst=/data
  - --mount
  - type=bind,src=/matrix/synapse/config,dst=/matrix-media-store-parent/media-store
  - --mount
  - type=bind,src=/var/docker_data/matrix/homeserver.db,dst=/homeserver.db
  - docker.io/matrixdotorg/synapse:v1.51.0
  - /usr/local/bin/synapse_port_db
  - --sqlite-database
  - /homeserver.db
  - --postgres-config
  - /data/homeserver.yaml
  delta: '0:00:02.075370'
  end: '2022-02-03 12:43:34.391324'
  msg: non-zero return code
  rc: 5
  start: '2022-02-03 12:43:32.315954'
  stderr: |-
    2022-02-03 12:43:33,934 - synapse.config.key - 147 - WARNING - This server is configured to use 'matrix.org' as its trusted key server via the
    'trusted_key_servers' config option. 'matrix.org' is a good choice for a key
    server since it is long-lived, stable and trusted. However, some admins may
    wish to use another server for this purpose.

    To suppress this warning and continue using 'matrix.org', admins should set
    'suppress_key_server_warning' to 'true' in homeserver.yaml.
    --------------------------------------------------------------------------------
    2022-02-03 12:43:33,969 - synapse.storage.prepare_database - 116 - INFO - ('main', 'state'): Checking existing schema version
    2022-02-03 12:43:33,972 - synapse.storage.prepare_database - 120 - INFO - ('main', 'state'): Existing schema is 67 (+0 deltas)
    2022-02-03 12:43:33,972 - synapse.storage.databases.main - 355 - INFO - Checking database for consistency with configuration...
    2022-02-03 12:43:33,972 - synapse_port_db - 722 - ERROR -
    Traceback (most recent call last):
      File "/usr/local/bin/synapse_port_db", line 570, in run
        self.sqlite_store = self.build_db_store(
      File "/usr/local/bin/synapse_port_db", line 536, in build_db_store
        prepare_database(db_conn, engine, config=self.hs_config)
      File "/usr/local/lib/python3.8/site-packages/synapse/storage/prepare_database.py", line 137, in prepare_database
        _upgrade_existing_database(
      File "/usr/local/lib/python3.8/site-packages/synapse/storage/prepare_database.py", line 380, in _upgrade_existing_database
        check_database_before_upgrade(cur, database_engine, config)
      File "/usr/local/lib/python3.8/site-packages/synapse/storage/databases/main/__init__.py", line 369, in check_database_before_upgrade
        raise Exception(
    Exception: Found users in database not native to example.com
    You cannot change a synapse server_name after it's been configured
    Traceback (most recent call last):
      File "/usr/local/bin/synapse_port_db", line 570, in run
        self.sqlite_store = self.build_db_store(
      File "/usr/local/bin/synapse_port_db", line 536, in build_db_store
        prepare_database(db_conn, engine, config=self.hs_config)
      File "/usr/local/lib/python3.8/site-packages/synapse/storage/prepare_database.py", line 137, in prepare_database
        _upgrade_existing_database(
      File "/usr/local/lib/python3.8/site-packages/synapse/storage/prepare_database.py", line 380, in _upgrade_existing_database
        check_database_before_upgrade(cur, database_engine, config)
      File "/usr/local/lib/python3.8/site-packages/synapse/storage/databases/main/__init__.py", line 369, in check_database_before_upgrade
        raise Exception(
    Exception: Found users in database not native to example.com!
    You cannot change a synapse server_name after it's been configured
    Found users in database not native to example.com!
    You cannot change a synapse server_name after it's been configured
  stderr_lines: <omitted>
  stdout: Preparing sqlite3...
  stdout_lines: <omitted>

PLAY RECAP *********************************************************************
matrix.example.com       : ok=14   changed=4    unreachable=0    failed=1    skipped=21   rescued=0    ignored=0
`

**Comment by spantaleev** [comment]
As it says:

> Exception: Found users in database not native to example.com!
You **cannot change a synapse server_name after it's been configured**
Found users in database not native to example.com!
You cannot change a synapse server_name after it's been configured

You either need to keep using your old domain with this database, or to start over with your new domain and a fresh database.

**Comment by DUCKCHI** [comment]
When I changed the domain, the domain error was resolved, but the following read-only error occurred.
The owner and group of homeserver.db were set as matrix, and the authority was given to 777, but it did not help solve the problem.

fatal: [matrix.example.com]: FAILED! => changed=true
  cmd:
  - docker
  - run
  - --rm
  - --name=matrix-synapse-migrate
  - --log-driver=none
  - --user=997:1002
  - --cap-drop=ALL
  - --network=matrix
  - --entrypoint=python
  - --mount
  - type=bind,src=/matrix/synapse/config,dst=/data
  - --mount
  - type=bind,src=/matrix/synapse/config,dst=/matrix-media-store-parent/media-store
  - --mount
  - type=bind,src=/home/ubuntu/dockers/matrix-docker-ansible-deploy/p.db,dst=/p.db
  - docker.io/matrixdotorg/synapse:v1.51.0
  - /usr/local/bin/synapse_port_db
  - --sqlite-database
  - /p.db
  - --postgres-config
  - /data/homeserver.yaml
  delta: '0:00:01.906222'
  end: '2022-02-03 14:26:56.094479'
  msg: non-zero return code
  rc: 5
  start: '2022-02-03 14:26:54.188257'
  stderr: |-
    2022-02-03 14:26:55,743 - synapse.config.key - 147 - WARNING - This server is configured to use 'matrix.org' as its trusted key server via the
    'trusted_key_servers' config option. 'matrix.org' is a good choice for a key
    server since it is long-lived, stable and trusted. However, some admins may
    wish to use another server for this purpose.

    To suppress this warning and continue using 'matrix.org', admins should set
    'suppress_key_server_warning' to 'true' in homeserver.yaml.
    --------------------------------------------------------------------------------
    2022-02-03 14:26:55,780 - synapse.storage.prepare_database - 116 - INFO - ('main', 'state'): Checking existing schema version
    2022-02-03 14:26:55,784 - synapse.storage.prepare_database - 120 - INFO - ('main', 'state'): Existing schema is 67 (+0 deltas)
    2022-02-03 14:26:55,785 - synapse.storage.databases.main - 355 - INFO - Checking database for consistency with configuration...
    2022-02-03 14:26:55,785 - synapse.storage.prepare_database - 412 - INFO - Applying schema deltas for v67
    2022-02-03 14:26:55,785 - synapse_port_db - 722 - ERROR -
    Traceback (most recent call last):
      File "/usr/local/bin/synapse_port_db", line 570, in run
        self.sqlite_store = self.build_db_store(
      File "/usr/local/bin/synapse_port_db", line 536, in build_db_store
        prepare_database(db_conn, engine, config=self.hs_config)
      File "/usr/local/lib/python3.8/site-packages/synapse/storage/prepare_database.py", line 137, in prepare_database
        _upgrade_existing_database(
      File "/usr/local/lib/python3.8/site-packages/synapse/storage/prepare_database.py", line 414, in _upgrade_existing_database
        cur.execute("DELETE FROM schema_version")
      File "/usr/local/lib/python3.8/site-packages/synapse/storage/database.py", line 310, in execute
        self._do_execute(self.txn.execute, sql, *args)
      File "/usr/local/lib/python3.8/site-packages/synapse/storage/database.py", line 343, in _do_execute
        return func(sql, *args)
    sqlite3.OperationalError: attempt to write a readonly database
    Traceback (most recent call last):
      File "/usr/local/bin/synapse_port_db", line 570, in run
        self.sqlite_store = self.build_db_store(
      File "/usr/local/bin/synapse_port_db", line 536, in build_db_store
        prepare_database(db_conn, engine, config=self.hs_config)
      File "/usr/local/lib/python3.8/site-packages/synapse/storage/prepare_database.py", line 137, in prepare_database
        _upgrade_existing_database(
      File "/usr/local/lib/python3.8/site-packages/synapse/storage/prepare_database.py", line 414, in _upgrade_existing_database
        cur.execute("DELETE FROM schema_version")
      File "/usr/local/lib/python3.8/site-packages/synapse/storage/database.py", line 310, in execute
        self._do_execute(self.txn.execute, sql, *args)
      File "/usr/local/lib/python3.8/site-packages/synapse/storage/database.py", line 343, in _do_execute
        return func(sql, *args)
    sqlite3.OperationalError: attempt to write a readonly database
    attempt to write a readonly database
  stderr_lines: <omitted>
  stdout: Preparing sqlite3...
  stdout_lines: <omitted>

**Comment by DUCKCHI** [comment]
I solved it.

After moving the DB file that you want to be right to /matrix/synapse/config/homeserver.db, it works by changing the owner to matrix and changing the authority to o+w.
