### ISSUE TITLE
mx-puppet-slack pre-built image fails to start

### ISSUE THREAD

**Issue by etkecc** [spantaleev/matrix-docker-ansible-deploy#1810]
**Describe the bug**
After the #1809 merge, the following issue occured with pre-built image:

```
May 10 15:07:28 matrix systemd[1]: Starting Matrix Mx Puppet Slack bridge...
May 10 15:07:33 matrix systemd[1]: Started Matrix Mx Puppet Slack bridge.
May 10 15:07:36 matrix matrix-mx-puppet-slack[407091]: internal/modules/cjs/loader.js:818
May 10 15:07:36 matrix matrix-mx-puppet-slack[407091]:   throw err;
May 10 15:07:36 matrix matrix-mx-puppet-slack[407091]:   ^
May 10 15:07:36 matrix matrix-mx-puppet-slack[407091]: Error: Cannot find module './matrixmessageparser'
May 10 15:07:36 matrix matrix-mx-puppet-slack[407091]: Require stack:
May 10 15:07:36 matrix matrix-mx-puppet-slack[407091]: - /opt/mx-puppet-slack/node_modules/@mx-puppet/matrix-slack-parser/lib/src/index.js
May 10 15:07:36 matrix matrix-mx-puppet-slack[407091]: - /opt/mx-puppet-slack/build/slack.js
May 10 15:07:36 matrix matrix-mx-puppet-slack[407091]: - /opt/mx-puppet-slack/build/index.js
May 10 15:07:36 matrix matrix-mx-puppet-slack[407091]:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
May 10 15:07:36 matrix matrix-mx-puppet-slack[407091]:     at Function.Module._load (internal/modules/cjs/loader.js:667:27)
May 10 15:07:36 matrix matrix-mx-puppet-slack[407091]:     at Module.require (internal/modules/cjs/loader.js:887:19)
May 10 15:07:36 matrix matrix-mx-puppet-slack[407091]:     at require (internal/modules/cjs/helpers.js:74:18)
May 10 15:07:36 matrix matrix-mx-puppet-slack[407091]:     at Object.<anonymous> (/opt/mx-puppet-slack/node_modules/@mx-puppet/matrix-slack-parser/lib/src/index.js:13:14)
May 10 15:07:36 matrix matrix-mx-puppet-slack[407091]:     at Module._compile (internal/modules/cjs/loader.js:999:30)
May 10 15:07:36 matrix matrix-mx-puppet-slack[407091]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
May 10 15:07:36 matrix matrix-mx-puppet-slack[407091]:     at Module.load (internal/modules/cjs/loader.js:863:32)
May 10 15:07:36 matrix matrix-mx-puppet-slack[407091]:     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
May 10 15:07:36 matrix matrix-mx-puppet-slack[407091]:     at Module.require (internal/modules/cjs/loader.js:887:19) {
May 10 15:07:36 matrix matrix-mx-puppet-slack[407091]:   code: 'MODULE_NOT_FOUND',
May 10 15:07:36 matrix matrix-mx-puppet-slack[407091]:   requireStack: [
May 10 15:07:36 matrix matrix-mx-puppet-slack[407091]:     '/opt/mx-puppet-slack/node_modules/@mx-puppet/matrix-slack-parser/lib/src/index.js',
May 10 15:07:36 matrix matrix-mx-puppet-slack[407091]:     '/opt/mx-puppet-slack/build/slack.js',
May 10 15:07:36 matrix matrix-mx-puppet-slack[407091]:     '/opt/mx-puppet-slack/build/index.js'
May 10 15:07:36 matrix matrix-mx-puppet-slack[407091]:   ]
May 10 15:07:36 matrix matrix-mx-puppet-slack[407091]: }
May 10 15:07:36 matrix systemd[1]: matrix-mx-puppet-slack.service: Main process exited, code=exited, status=1/FAILURE
May 10 15:07:36 matrix systemd[1]: matrix-mx-puppet-slack.service: Failed with result 'exit-code'.
```

**To Reproduce**

No special steps, just try to run mx-puppet-slack

**Expected behavior**

It works

**Matrix Server:**
 - OS: Ubuntu 22.04
 - Architecture amd64

**Ansible:**

Not an ansible problem

**Additional context**
N/A

**Comment by dsonck92** [comment]
Ah yes, this is a pretty silly NPM -> Yarn mistake on my part. Tracked by https://gitlab.com/mx-puppet/slack/mx-puppet-slack/-/issues/135

**Comment by dsonck92** [comment]
@spantaleev / @etkecc I have pushed some changes that I believe should fix the issue, could either of you please check with this image?

```
registry.gitlab.com/mx-puppet/slack/mx-puppet-slack:acceptance-fix-matrix-slack-parser
```

While I'm looking over all puppet bridges and improving the general pipelines, I actually don't run it myself (yet, but might do so as work uses slack) so I don't really have an install to test with. If either of you could confirm it works, I can merge it in, and do an official release.

**Comment by etkecc** [comment]
unfortunately, won't be able to test it today

**Comment by dsonck92** [comment]
@spantaleev the fix for the package has been tested, version v0.1.1 should be out soon.

**Comment by dsonck92** [comment]
Or rather, it is out now.
