### ISSUE TITLE
Unable to re-run playbook to install Synapse-admin

### ISSUE THREAD

**Issue by danb35** [spantaleev/matrix-docker-ansible-deploy#2317]
**Describe the bug**
I used the playbook to set up Synapse on an Oracle Cloud A1 (ARM64-based) instance, and it ran through smoothly.  I created an admin and a non-admin user, they're able to log in to Element, and everything seems right.  I now want to add Synapse-admin, so I added `matrix_synapse_admin_enabled: true` to the end of `vars.yml`.  And now, when I run it, it fails with this error:
```
TASK [galaxy/geerlingguy.docker : Add Docker repository.] *************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: apt_pkg.Error: E:Conflicting values set for option Signed-By regarding source https://download.docker.com/linux/ubuntu/ jammy: /etc/apt/keyrings/docker.gpg != , E:The list of sources could not be read.
fatal: [matrix.db5.us]: FAILED! => changed=false
  module_stderr: |-
    Traceback (most recent call last):
      File "<stdin>", line 107, in <module>
      File "<stdin>", line 99, in _ansiballz_main
      File "<stdin>", line 47, in invoke_module
      File "/usr/lib/python3.10/runpy.py", line 224, in run_module
        return _run_module_code(code, init_globals, run_name, mod_spec)
      File "/usr/lib/python3.10/runpy.py", line 96, in _run_module_code
        _run_code(code, mod_globals, init_globals,
      File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
        exec(code, run_globals)
      File "/tmp/ansible_apt_repository_payload_105g4x38/ansible_apt_repository_payload.zip/ansible/modules/apt_repository.py", line 679, in <module>
      File "/tmp/ansible_apt_repository_payload_105g4x38/ansible_apt_repository_payload.zip/ansible/modules/apt_repository.py", line 656, in main
      File "/usr/lib/python3/dist-packages/apt/cache.py", line 152, in __init__
        self.open(progress)
      File "/usr/lib/python3/dist-packages/apt/cache.py", line 214, in open
        self._cache = apt_pkg.Cache(progress)
    apt_pkg.Error: E:Conflicting values set for option Signed-By regarding source https://download.docker.com/linux/ubuntu/ jammy: /etc/apt/keyrings/docker.gpg != , E:The list of sources could not be read.
  module_stdout: ''
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
  rc: 1
```

**To Reproduce**
My `vars.yml` file looks like this:

```yaml
---
    # The bare domain name which represents your Matrix identity.
    # Matrix user ids for your server will be of the form (`@user:<matrix-domain>`).
    #
    # Note: this playbook does not touch the server referenced here.
    # Installation happens on another server ("matrix.<matrix-domain>").
    #
    # If you've deployed using the wrong domain, you'll have to run the Uninstalling step,
    # because you can't change the Domain after deployment.
    #
    # Example value: example.com
    matrix_domain: domain.us
    
    # The Matrix homeserver software to install.
    # See:
    #  - `roles/custom/matrix-base/defaults/main.yml` for valid options
    # - the `docs/configuring-playbook-IMPLEMENTATION_NAME.md` documentation page, if one is available for your implementation choice
    matrix_homeserver_implementation: synapse
    
    # Serve base domain on this instance
    matrix_nginx_proxy_base_domain_serving_enabled: true
    
    # A secret used as a base, for generating various other secrets.
    # You can put any string here, but generating a strong one is preferred (e.g. `pwgen -s 64 1`).
    matrix_homeserver_generic_secret_key: ''
    
    # This is something which is provided to Let's Encrypt when retrieving SSL certificates for domains.
    #
    # In case SSL renewal fails at some point, you'll also get an email notification there.
    #
    # If you decide to use another method for managing SSL certificates (different than the default Let's Encrypt),
    # you won't be required to define this variable (see `docs/configuring-playbook-ssl-certificates.md`).
    #
    # Example value: someone@example.com
    matrix_ssl_lets_encrypt_support_email: 'admin@domain.org'
    
    # A Postgres password to use for the superuser Postgres user (called `matrix` by default).
    #
    # The playbook creates additional Postgres users and databases (one for each enabled service)
    # using this superuser account.
    devture_postgres_connection_password: ''
    
    matrix_etherpad_enabled: false
    
    # Uncomment below if you'd like to install Etherpad on the Dimension domain (not recommended)
    # matrix_etherpad_mode: dimension
    
    # Uncomment below to enable the admin web UI
    # matrix_etherpad_admin_username: etherpad_admin
    # matrix_etherpad_admin_password: 
    
    matrix_prometheus_enabled: true
    
    # You can remove this, if unnecessary.
    matrix_prometheus_node_exporter_enabled: true
    
    # You can remove this, if unnecessary.
    matrix_prometheus_postgres_exporter_enabled: true
    
    matrix_grafana_enabled: true
    
    matrix_grafana_anonymous_access: false
    
    # This has no relation to your Matrix user id. It can be any username you'd like.
    # Changing the username subsequently won't work.
    matrix_grafana_default_admin_user: "matrix_grafana_admin"
    
    # Changing the password subsequently won't work.
    matrix_grafana_default_admin_password: ""
    
    # Pull all Element themes
    matrix_client_element_themes_enabled: true
    
    # Install Hydrogen
    matrix_client_hydrogen_enabled: true
    
    # Install Cinny
    matrix_client_cinny_enabled: true
    
    # Enable telemetry
    matrix_synapse_report_stats: true # for synapse 
    
    matrix_dendrite_report_stats: true # for dendrite 
    
    # Install Synapse Admin
    matrix_synapse_admin_enabled: true
```

Running `ansible-playbook -K -i inventory/hosts setup.yml --tags=setup-all,start` with the vars.yml above results in the error noted above.

**Expected behavior**
Expected behavior is that the playbook would run successfully and install Synapse-admin

**Matrix Server:**
 - OS: Ubuntu 22.04.1
 - Architecture: arm64

**Ansible:**
If your problem appears to be with Ansible, tell us:
- I'm running Ansible on my Mac, running osX Ventura 13.0
- what version of Ansible you're running (see `ansible --version`)
```
 dan@Dan-Mac-Mini-2  ~  ansible --version
ansible [core 2.13.6]
  config file = None
  configured module search path = ['/Users/dan/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/6.6.0/libexec/lib/python3.10/site-packages/ansible
  ansible collection location = /Users/dan/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.10.8 (main, Nov 15 2022, 05:25:54) [Clang 14.0.0 (clang-1400.0.29.202)]
  jinja version = 3.1.2
  libyaml = True
```

**Additional context**
Before the last successful attempt to run this, I had a few unsuccessful attempts, failing in different ways (python3-docker not installed, docker itself not installed, security policy not configured properly to open the necessary ports, etc.).  On the last of these failures, I got, if not exactly the same error message noted above, at least a very similar one.  At that point, I destroyed the VM entirely and started over with a fresh one.  Thus, I don't think this error is unique to trying to install synapse-admin.

**Comment by spantaleev** [comment]
Your problem is with your Ubuntu apt sources for installing Docker. Check `/etc/apt/sources.d` or something. You probably have multiple Docker repos, some with `signed-by`, others without.

**Comment by danb35** [comment]
I do.  The first follows the Docker [installation instructions](https://docs.docker.com/engine/install/ubuntu/), and is at /etc/apt/sources.list.d/docker.list, containing:
```
deb [arch=arm64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu jammy stable
```
...and the second is at `download_docker_com_linux_ubuntu.list`, containing:
```
deb [arch=arm64] https://download.docker.com/linux/ubuntu jammy stable
```
I note that I wasn't able to run the installation at all without Docker being installed on the VM already.  But since the second .list file is clearly the one installed by the playbook, should I delete the first one?

**Comment by spantaleev** [comment]
You could give that a try and rely solely on the playbook for managing your Docker installation.

**Comment by danb35** [comment]
Deleting `docker.list` did let the rest of the installation complete.  Which leaves the question of why I had to manually install Docker to get the first installation to run, but I guess that'd be a subject for a different ticket.

**Comment by spantaleev** [comment]
Not sure why.. My experiments with an Ubuntu 22.04 VM from some week ago (or so) indicate that the playbook can install Docker by itself on a bare server. Not sure what could have failed on your setup. If you can gather more information or replicate it, please let us know!

**Comment by ata-star** [comment]
Had this issue too,  #2359 made me manually install docker @spantaleev
