### ISSUE TITLE
chat-gpt crashes after start

### ISSUE THREAD

**Issue by thigg** [spantaleev/matrix-docker-ansible-deploy#2395]
**Describe the bug**
the chatgpt service is not starting. Logs below

**To Reproduce**
Install chatgpt according to docs

**Expected behavior**
service does not fail

**Matrix Server:**
 - OS: [e.g. Ubuntu 21.04]  
 ```
# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.1 LTS
Release:	22.04
Codename:	jammy
 ```
 - Architecture [e.g. amd64, arm32, arm64] x64

**Ansible:**
If your problem appears to be with Ansible, tell us:
- remote on the root account of a vm
- 

**Additional context**
```
Jan 14 11:28:57 nextcloud matrix-bot-chatgpt[2448935]: warning Skipping preferred cache folder "/.cache/yarn" because it is not writable.
Jan 14 11:28:57 nextcloud matrix-bot-chatgpt[2448935]: warning Selected the next writable cache folder in the list, will be "/tmp/.yarn-cache-998".
Jan 14 11:28:57 nextcloud matrix-bot-chatgpt[2448935]: $ node dist/index.js
Jan 14 11:28:57 nextcloud matrix-bot-chatgpt[2448935]: warning Cannot find a suitable global folder. Tried these: "/usr/local, /.yarn"
Jan 14 11:28:59 nextcloud matrix-bot-chatgpt[2448935]: /usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserRunner.js:299
Jan 14 11:28:59 nextcloud matrix-bot-chatgpt[2448935]:             reject(new Error([
Jan 14 11:28:59 nextcloud matrix-bot-chatgpt[2448935]:                    ^
Jan 14 11:28:59 nextcloud matrix-bot-chatgpt[2448935]: Error: Failed to launch the browser process!
Jan 14 11:28:59 nextcloud matrix-bot-chatgpt[2448935]: find: '//.config/chromium/Crash Reports/pending/': No such file or directory
Jan 14 11:28:59 nextcloud matrix-bot-chatgpt[2448935]: chrome_crashpad_handler: --database is required
Jan 14 11:28:59 nextcloud matrix-bot-chatgpt[2448935]: Try 'chrome_crashpad_handler --help' for more information.
Jan 14 11:28:59 nextcloud matrix-bot-chatgpt[2448935]: [59:59:0114/112859.261675:ERROR:socket.cc(120)] recvmsg: Connection reset by peer (104)
Jan 14 11:28:59 nextcloud matrix-bot-chatgpt[2448935]: TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md
Jan 14 11:28:59 nextcloud matrix-bot-chatgpt[2448935]:     at onClose (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserRunner.js:299:20)
Jan 14 11:28:59 nextcloud matrix-bot-chatgpt[2448935]:     at Interface.<anonymous> (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserRunner.js:287:24)
Jan 14 11:28:59 nextcloud matrix-bot-chatgpt[2448935]:     at Interface.emit (node:events:525:35)
Jan 14 11:28:59 nextcloud matrix-bot-chatgpt[2448935]:     at Interface.close (node:internal/readline/interface:534:10)
Jan 14 11:28:59 nextcloud matrix-bot-chatgpt[2448935]:     at Socket.onend (node:internal/readline/interface:260:10)
Jan 14 11:28:59 nextcloud matrix-bot-chatgpt[2448935]:     at Socket.emit (node:events:525:35)
Jan 14 11:28:59 nextcloud matrix-bot-chatgpt[2448935]:     at endReadableNT (node:internal/streams/readable:1359:12)
Jan 14 11:28:59 nextcloud matrix-bot-chatgpt[2448935]:     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Jan 14 11:28:59 nextcloud matrix-bot-chatgpt[2448935]: Node.js v19.4.0
```

**Comment by thigg** [comment]
Just seen this 

> This means that you currently can't log in with your laptop and then run the bot on a server or proxy somewhere.

in the bot documentation. Would be helpful to include this in the install instructions ;)

**Comment by alpha41** [comment]
I have the same problem that my ChatGPT container crashes right after startup with the same error message.

At the same time I am neither logged in with the bot user in Matrix nor in OpenAI with my corresponding user.
I have tried both the current version 1.2.3 and 1.2.2 of the ChatGPT container.

**Comment by shreyasajj** [comment]
It looks like this issue was because of a home directory not being setup

**Comment by shreyasajj** [comment]
At least the error is gone for me in the new update
