### ISSUE TITLE
Discord Bridge - The field data.auth.clientID is ******* which is the wrong type

### ISSUE THREAD

**Issue by dacruz21** [spantaleev/matrix-docker-ansible-deploy#240]
Hello!

I am running into an issue with the Discord bridge. It appears that the `matrix_appservice_discord_client_id` is being passed as a string when it should be passed as a number (or possibly vice versa).

It looks like this has already been discovered and a fix was attempted in this commit: https://github.com/spantaleev/matrix-docker-ansible-deploy/commit/87e3650327f159a5a987296ac733e35c4697be88 but it still isn't working for me.

Logs:
```
Aug 10 08:04:21 casa matrix-appservice-discord[1890]: {"field":"data.auth.clientID","message":"is the wrong type","value":1234,"type":"string","schemaPath":["properties","auth","properties","clientID"]}
Aug 10 08:04:21 casa matrix-appservice-discord[1890]: The field data.auth.clientID is 1234 which is the wrong type
Aug 10 08:04:21 casa matrix-appservice-discord[1890]: Aug-10 08:04:21.737 [DiscordAS] error: Failed to start bridge.
Aug 10 08:04:21 casa matrix-appservice-discord[1890]: Aug-10 08:04:21.810 [DiscordAS] error: Error: Failed to validate file
Aug 10 08:04:21 casa matrix-appservice-discord[1890]:     at ConfigValidator.validate (/node_modules/matrix-appservice-bridge/lib/components/config-validator.js:42:17)
Aug 10 08:04:21 casa matrix-appservice-discord[1890]:     at Cli._loadConfig (/node_modules/matrix-appservice-bridge/lib/components/cli.js:160:22)
Aug 10 08:04:21 casa matrix-appservice-discord[1890]:     at Cli._assignConfigFile (/node_modules/matrix-appservice-bridge/lib/components/cli.js:145:23)
Aug 10 08:04:21 casa matrix-appservice-discord[1890]:     at Cli.run (/node_modules/matrix-appservice-bridge/lib/components/cli.js:139:10)
Aug 10 08:04:21 casa matrix-appservice-discord[1890]:     at Object.<anonymous> (/src/discordas.ts:40:9)
Aug 10 08:04:21 casa matrix-appservice-discord[1890]:     at Module._compile (internal/modules/cjs/loader.js:774:30)
Aug 10 08:04:21 casa matrix-appservice-discord[1890]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
Aug 10 08:04:21 casa matrix-appservice-discord[1890]:     at Module.load (internal/modules/cjs/loader.js:641:32)
Aug 10 08:04:21 casa matrix-appservice-discord[1890]:     at Function.Module._load (internal/modules/cjs/loader.js:556:12)
Aug 10 08:04:21 casa matrix-appservice-discord[1890]:     at Function.Module.runMain (internal/modules/cjs/loader.js:837:10)
Aug 10 08:04:21 casa matrix-appservice-discord[1890]:     at internal/main/run_main_module.js:17:11 {
Aug 10 08:04:21 casa matrix-appservice-discord[1890]:   _validationErrors: [
Aug 10 08:04:21 casa matrix-appservice-discord[1890]:     {
Aug 10 08:04:21 casa matrix-appservice-discord[1890]:       field: 'data.auth.clientID',
Aug 10 08:04:21 casa matrix-appservice-discord[1890]:       message: 'is the wrong type',
Aug 10 08:04:21 casa matrix-appservice-discord[1890]:       value: 1234,
Aug 10 08:04:21 casa matrix-appservice-discord[1890]:       type: 'string',
Aug 10 08:04:21 casa matrix-appservice-discord[1890]:       schemaPath: [Array]
Aug 10 08:04:21 casa matrix-appservice-discord[1890]:     }
Aug 10 08:04:21 casa matrix-appservice-discord[1890]:   ]
Aug 10 08:04:21 casa matrix-appservice-discord[1890]: }
```

I've sanitized the actual client ID for obvious reasons. Also of note, the value that is logged is the value that I've provided in my host vars, but *rounded to the nearest thousands place*. No clue why that could be.

**Comment by dacruz21** [comment]
I've tried reverting the change in https://github.com/spantaleev/matrix-docker-ansible-deploy/commit/87e3650327f159a5a987296ac733e35c4697be88 but to no avail

I tried:
1. Removing the `| string`
2. Changing my client ID in my host vars to an integer instead of a string
3. Deleting /matrix/appservice-discord on the host
4. Re-deploying

**Comment by spantaleev** [comment]
Thanks for bringing this up again! I believe I've fixed it properly this time.

**Comment by dacruz21** [comment]
Fix confirmed! Thank you very much!
