### ISSUE TITLE
Error while using own Traefik and own SSL-Certs

### ISSUE THREAD

**Issue by JohannesFleischer** [spantaleev/matrix-docker-ansible-deploy#2598]
**Playbook Configuration**:

My `vars.yml` file looks like this:

```yaml
---
# The bare domain name which represents your Matrix identity.
# Matrix user ids for your server will be of the form (`@user:<matrix-domain>`).

# Beware, you can't change the Domain after deployment.
matrix_domain: "<Domain>"

#######################

# Custom subdomain
matrix_server_fqn_matrix: "chat.{{ matrix_domain }}"
matrix_server_fqn_element: "element.{{ matrix_domain }}"


#######################
# disable/restrict federation:

# disable:
matrix_synapse_federation_domain_whitelist: []

# restrict:
#matrix_synapse_federation_domain_whitelist:
#- example.com
#- another.com

#######################
# The Matrix homeserver
matrix_homeserver_implementation: "synapse"

#######################
# traefik
#see `docs/configuring-playbook-own-webserver.md`.

matrix_playbook_reverse_proxy_type: other-traefik-container
matrix_playbook_reverse_proxyable_services_additional_network: traefik
devture_traefik_certs_dumper_ssl_dir_path: "<path>"

##########################
# secrets

# A secret used as a base, for generating various other secrets.
matrix_homeserver_generic_secret_key: "<password>"

# possible fix for a second run:
#matrix_homeserver_generic_secret_key: "{{ matrix_synapse_macaroon_secret_key }}"

#####

# A Postgres password to use for the superuser Postgres user (called `matrix` by default).
#
# The playbook creates additional Postgres users and databases (one for each enabled service)
# using this superuser account.
devture_postgres_connection_password: "<password>"


##########################
# jitsi

matrix_jitsi_enabled: true

# you can run `bash inventory/scripts/jitsi-generate-passwords.sh` to generate these passwords,
matrix_jitsi_jicofo_auth_password: "<password>"
matrix_jitsi_jvb_auth_password: "<password>"
matrix_jitsi_jibri_recorder_password: "<password>"
matrix_jitsi_jibri_xmpp_password: "<password>"

##########################
# signal bridge

matrix_mautrix_signal_enabled: true

matrix_synapse_ext_password_provider_shared_secret_auth_enabled: true
matrix_synapse_ext_password_provider_shared_secret_auth_shared_secret: "<password>"


##########################
# account creation

# enable registration
matrix_synapse_enable_registration: True
# disable verification
matrix_synapse_enable_registration_without_verification: True

##########################
# enable admin ui 
matrix_synapse_admin_enabled: true

##########################
# setup mail relay

matrix_mailer_sender_address: "email@address.tld"
matrix_mailer_relay_use: true
matrix_mailer_relay_host_name: "mail.address.tld"
matrix_mailer_relay_host_port: 587
matrix_mailer_relay_auth: true
matrix_mailer_relay_auth_username: "email@address.tld"
matrix_mailer_relay_auth_password: "<password>"

```

**Matrix Server:**
 - OS: Debian GNU/Linux 11 (bullseye)
 - Architecture: amd64

**Ansible:**
- run on other machine: Ubuntu 22.04 
- standalone ansible 2.14.3

**Problem description**:

I am trying to install Matrix on a server that is already running a Traefik and that already has SSL certificates that I want to use.

Therefore, I tried to set in the playbook the Traefik I manage and also the folder where my SSL certificates are located.

However, I get errors on execution that values like `matrix_ssl_lets_encrypt_support_email` are not defined, although I do not want to generate certificates.

Also, the setting of `matrix_ssl_retrieval_method: none` did not work.

 I would like to avoid the usage of a second Traefik.

**Additional context**
Errormsg:
```sh
TASK [custom/matrix-jitsi : Ensure jitsi-web environment variables file created] **********
task path: [...]/roles/custom/matrix-jitsi/tasks/setup_jitsi_web_install.yml:28
<IP> ESTABLISH SSH CONNECTION FOR USER: root
<IP> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="root"' -o ConnectTimeout=10 -o 'ControlPath="/home/<User>/.ansible/cp/dd940ddfba"' <IP> '/bin/sh -c '"'"'echo ~root && sleep 0'"'"''
<IP> (0, b'/root\n', b'')
<IP> ESTABLISH SSH CONNECTION FOR USER: root
<IP> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="root"' -o ConnectTimeout=10 -o 'ControlPath="/home/<User>/.ansible/cp/dd940ddfba"' <IP> '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo /root/.ansible/tmp `"&& mkdir "` echo /root/.ansible/tmp/ansible-tmp-1679561781.7088358-114497-155479149421210 `" && echo ansible-tmp-1679561781.7088358-114497-155479149421210="` echo /root/.ansible/tmp/ansible-tmp-1679561781.7088358-114497-155479149421210 `" ) && sleep 0'"'"''
<IP> (0, b'ansible-tmp-1679561781.7088358-114497-155479149421210=/root/.ansible/tmp/ansible-tmp-1679561781.7088358-114497-155479149421210\n', b'')
<IP> ESTABLISH SSH CONNECTION FOR USER: root
<IP> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="root"' -o ConnectTimeout=10 -o 'ControlPath="/home/<User>/.ansible/cp/dd940ddfba"' <IP> '/bin/sh -c '"'"'rm -f -r /root/.ansible/tmp/ansible-tmp-1679561781.7088358-114497-155479149421210/ > /dev/null 2>&1 && sleep 0'"'"''
<IP> (0, b'', b'')
The full traceback is:
Traceback (most recent call last):
  File "/home/<User>/.local/lib/python3.10/site-packages/ansible/template/__init__.py", line 987, in do_template
    res = self.environment.concat(rf)
  File "/home/<User>/.local/lib/python3.10/site-packages/ansible/template/native_helpers.py", line 88, in ansible_concat
    return ''.join([to_text(v) for v in nodes])
  File "/home/<User>/.local/lib/python3.10/site-packages/ansible/template/native_helpers.py", line 88, in <listcomp>
    return ''.join([to_text(v) for v in nodes])
  File "<template>", line 59, in root
  File "/home/<User>/.local/lib/python3.10/site-packages/ansible/template/__init__.py", line 262, in wrapper
    ret = func(*args, **kwargs)
  File "/home/<User>/.local/lib/python3.10/site-packages/ansible/template/__init__.py", line 511, in _ansible_finalize
    return thing if _fail_on_undefined(thing) is not None else ''
  File "/home/<User>/.local/lib/python3.10/site-packages/ansible/template/__init__.py", line 483, in _fail_on_undefined
    elif is_sequence(data):
  File "/home/<User>/.local/lib/python3.10/site-packages/ansible/module_utils/common/collections.py", line 94, in is_sequence
    if not include_strings and is_string(seq):
  File "/home/<User>/.local/lib/python3.10/site-packages/jinja2/runtime.py", line 852, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: 'matrix_ssl_lets_encrypt_support_email' is undefined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/<User>/.local/lib/python3.10/site-packages/ansible/plugins/action/template.py", line 141, in run
    resultant = templar.do_template(template_data, preserve_trailing_newlines=True, escape_backslashes=False)
  File "/home/<User>/.local/lib/python3.10/site-packages/ansible/template/__init__.py", line 1021, in do_template
    raise AnsibleUndefinedVariable(e, orig_exc=e)
ansible.errors.AnsibleUndefinedVariable: 'matrix_ssl_lets_encrypt_support_email' is undefined. 'matrix_ssl_lets_encrypt_support_email' is undefined
fatal: [<Server>]: FAILED! => {
    "changed": false,
    "msg": "AnsibleUndefinedVariable: 'matrix_ssl_lets_encrypt_support_email' is undefined. 'matrix_ssl_lets_encrypt_support_email' is undefined"
}

PLAY RECAP ********************************************************************************
<Server>                     : ok=129  changed=6    unreachable=0    failed=1    skipped=127  rescued=0    ignored=0 
```

**Comment by michDeca** [comment]
(I'm not quite sure, however): The problem occurred in matrix-jitsi. According to the [changeLog](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/1d00d15482e8a2ec9e82a50624eda846ecf834d1/CHANGELOG.md#the-matrix-jitsi-role-lives-independently-now) this part has been relocated. 
Did you check if your problem still happens with the newest version?

**Comment by JohannesFleischer** [comment]
Fixed it a while ago. Forgot to close the issue.
