### ISSUE TITLE
beeper-linkedin is not starting

### ISSUE THREAD

**Issue by nebocamin** [spantaleev/matrix-docker-ansible-deploy#2908]
the bridge worked until the last update 2 days ago

```
Sep 21 01:02:29 matrix.xxxxx matrix-beeper-linkedin[2058838]:     return await self._protocol.query(query, timeout)
Sep 21 01:02:29 matrix.xxxxx matrix-beeper-linkedin[2058838]:   File "asyncpg/protocol/protocol.pyx", line 338, in query
Sep 21 01:02:29 matrix.xxxxx matrix-beeper-linkedin[2058838]: asyncpg.exceptions.PostgresSyntaxError: syntax error at or near "user"
Sep 21 01:02:29 matrix.xxxxx systemd[1]: matrix-beeper-linkedin.service: Main process exited, code=exited, status=25/n/a
Sep 21 01:02:29 matrix.xxxxx systemd[1]: matrix-beeper-linkedin.service: Failed with result 'exit-code'.
```

will further investigate tomorrow.

**Comment by nebocamin** [comment]
hm.. it stays that way. 

```
Sep 22 23:09:39 matrix.xxxxxx.xxx systemd[1]: Started Matrix Beeper Linkedin bridge.
Sep 22 23:09:42 matrix.xxxxxx.xxx matrix-beeper-linkedin[3013265]: [2023-09-22 21:09:42,612] [CRITICAL@mau.init] Failed to initialize database
Sep 22 23:09:42 matrix.xxxxxx.xxx matrix-beeper-linkedin[3013265]: Traceback (most recent call last):
Sep 22 23:09:42 matrix.xxxxxx.xxx matrix-beeper-linkedin[3013265]:   File "/usr/lib/python3.10/site-packages/mautrix/bridge/bridge.py", line 216, in start_db
Sep 22 23:09:42 matrix.xxxxxx.xxx matrix-beeper-linkedin[3013265]:     await self.db.start()
Sep 22 23:09:42 matrix.xxxxxx.xxx matrix-beeper-linkedin[3013265]:   File "/usr/lib/python3.10/site-packages/mautrix/util/async_db/asyncpg.py", line 72, in start
Sep 22 23:09:42 matrix.xxxxxx.xxx matrix-beeper-linkedin[3013265]:     await super().start()
Sep 22 23:09:42 matrix.xxxxxx.xxx matrix-beeper-linkedin[3013265]:   File "/usr/lib/python3.10/site-packages/mautrix/util/async_db/database.py", line 105, in start
Sep 22 23:09:42 matrix.xxxxxx.xxx matrix-beeper-linkedin[3013265]:     await self.upgrade_table.upgrade(self)
Sep 22 23:09:42 matrix.xxxxxx.xxx matrix-beeper-linkedin[3013265]:   File "/usr/lib/python3.10/site-packages/mautrix/util/async_db/upgrade.py", line 137, in upgrade
Sep 22 23:09:42 matrix.xxxxxx.xxx matrix-beeper-linkedin[3013265]:     version = await upgrade(conn, db.scheme) or new_version
Sep 22 23:09:42 matrix.xxxxxx.xxx matrix-beeper-linkedin[3013265]:   File "/usr/lib/python3.10/site-packages/mautrix/util/async_db/upgrade.py", line 35, in _wrapper
Sep 22 23:09:42 matrix.xxxxxx.xxx matrix-beeper-linkedin[3013265]:     return await _wrapped(conn)
Sep 22 23:09:42 matrix.xxxxxx.xxx matrix-beeper-linkedin[3013265]:   File "/usr/lib/python3.10/site-packages/linkedin_matrix/db/upgrade/v08_splat_pickle_data.py", line 14, in upgrade_v8
Sep 22 23:09:42 matrix.xxxxxx.xxx matrix-beeper-linkedin[3013265]:     await conn.execute("ALTER TABLE user ADD COLUMN jsessionid string")
Sep 22 23:09:42 matrix.xxxxxx.xxx matrix-beeper-linkedin[3013265]:   File "/usr/lib/python3.10/site-packages/mautrix/util/async_db/connection.py", line 38, in wrapper
Sep 22 23:09:42 matrix.xxxxxx.xxx matrix-beeper-linkedin[3013265]:     ret = await func(self, arg, *args, **kwargs)
Sep 22 23:09:42 matrix.xxxxxx.xxx matrix-beeper-linkedin[3013265]:   File "/usr/lib/python3.10/site-packages/mautrix/util/async_db/connection.py", line 81, in execute
Sep 22 23:09:42 matrix.xxxxxx.xxx matrix-beeper-linkedin[3013265]:     return await self.wrapped.execute(query, *args, timeout=timeout)
Sep 22 23:09:42 matrix.xxxxxx.xxx matrix-beeper-linkedin[3013265]:   File "/usr/lib/python3.10/site-packages/asyncpg/connection.py", line 317, in execute
Sep 22 23:09:42 matrix.xxxxxx.xxx matrix-beeper-linkedin[3013265]:     return await self._protocol.query(query, timeout)
Sep 22 23:09:42 matrix.xxxxxx.xxx matrix-beeper-linkedin[3013265]:   File "asyncpg/protocol/protocol.pyx", line 338, in query
Sep 22 23:09:42 matrix.xxxxxx.xxx matrix-beeper-linkedin[3013265]: asyncpg.exceptions.PostgresSyntaxError: syntax error at or near "user"
Sep 22 23:09:43 matrix.xxxxxx.xxx systemd[1]: matrix-beeper-linkedin.service: Main process exited, code=exited, status=25/n/a
Sep 22 23:09:43 matrix.xxxxxx.xxx systemd[1]: matrix-beeper-linkedin.service: Failed with result 'exit-code'.
```

**Comment by spantaleev** [comment]
The bridge is broken upstream. Consider reporting this directly to its developers

**Comment by sumnerevans** [comment]
This has been fixed in https://github.com/beeper/linkedin/commit/b8d41288a906196211cbbab92346b5902125feb4

**Comment by nebocamin** [comment]
@sumnerevans it changed into asyncpg.exceptions.UndefinedObjectError: type "string" does not exist

```
Sep 24 21:46:21 matrix.xxxxxx.xxx systemd[1]: matrix-beeper-linkedin.service: Scheduled restart job, restart counter is at 13.
Sep 24 21:46:21 matrix.xxxxxx.xxx systemd[1]: Stopped Matrix Beeper Linkedin bridge.
Sep 24 21:46:21 matrix.xxxxxx.xxx systemd[1]: Starting Matrix Beeper Linkedin bridge...
Sep 24 21:46:26 matrix.xxxxxx.xxx systemd[1]: Started Matrix Beeper Linkedin bridge.
Sep 24 21:46:30 matrix.xxxxxx.xxx matrix-beeper-linkedin[3303934]: [2023-09-24 19:46:30,080] [CRITICAL@mau.init] Failed to initialize database
Sep 24 21:46:30 matrix.xxxxxx.xxx matrix-beeper-linkedin[3303934]: Traceback (most recent call last):
Sep 24 21:46:30 matrix.xxxxxx.xxx matrix-beeper-linkedin[3303934]:   File "/usr/lib/python3.10/site-packages/mautrix/bridge/bridge.py", line 216, in start_db
Sep 24 21:46:30 matrix.xxxxxx.xxx matrix-beeper-linkedin[3303934]:     await self.db.start()
Sep 24 21:46:30 matrix.xxxxxx.xxx matrix-beeper-linkedin[3303934]:   File "/usr/lib/python3.10/site-packages/mautrix/util/async_db/asyncpg.py", line 72, in start
Sep 24 21:46:30 matrix.xxxxxx.xxx matrix-beeper-linkedin[3303934]:     await super().start()
Sep 24 21:46:30 matrix.xxxxxx.xxx matrix-beeper-linkedin[3303934]:   File "/usr/lib/python3.10/site-packages/mautrix/util/async_db/database.py", line 105, in start
Sep 24 21:46:30 matrix.xxxxxx.xxx matrix-beeper-linkedin[3303934]:     await self.upgrade_table.upgrade(self)
Sep 24 21:46:30 matrix.xxxxxx.xxx matrix-beeper-linkedin[3303934]:   File "/usr/lib/python3.10/site-packages/mautrix/util/async_db/upgrade.py", line 137, in upgrade
Sep 24 21:46:30 matrix.xxxxxx.xxx matrix-beeper-linkedin[3303934]:     version = await upgrade(conn, db.scheme) or new_version
Sep 24 21:46:30 matrix.xxxxxx.xxx matrix-beeper-linkedin[3303934]:   File "/usr/lib/python3.10/site-packages/mautrix/util/async_db/upgrade.py", line 35, in _wrapper
Sep 24 21:46:30 matrix.xxxxxx.xxx matrix-beeper-linkedin[3303934]:     return await _wrapped(conn)
Sep 24 21:46:30 matrix.xxxxxx.xxx matrix-beeper-linkedin[3303934]:   File "/usr/lib/python3.10/site-packages/linkedin_matrix/db/upgrade/v08_splat_pickle_data.py", line 14, in upgrade_v8
Sep 24 21:46:30 matrix.xxxxxx.xxx matrix-beeper-linkedin[3303934]:     await conn.execute('ALTER TABLE "user" ADD COLUMN jsessionid string')
Sep 24 21:46:30 matrix.xxxxxx.xxx matrix-beeper-linkedin[3303934]:   File "/usr/lib/python3.10/site-packages/mautrix/util/async_db/connection.py", line 38, in wrapper
Sep 24 21:46:30 matrix.xxxxxx.xxx matrix-beeper-linkedin[3303934]:     ret = await func(self, arg, *args, **kwargs)
Sep 24 21:46:30 matrix.xxxxxx.xxx matrix-beeper-linkedin[3303934]:   File "/usr/lib/python3.10/site-packages/mautrix/util/async_db/connection.py", line 81, in execute
Sep 24 21:46:30 matrix.xxxxxx.xxx matrix-beeper-linkedin[3303934]:     return await self.wrapped.execute(query, *args, timeout=timeout)
Sep 24 21:46:30 matrix.xxxxxx.xxx matrix-beeper-linkedin[3303934]:   File "/usr/lib/python3.10/site-packages/asyncpg/connection.py", line 317, in execute
Sep 24 21:46:30 matrix.xxxxxx.xxx matrix-beeper-linkedin[3303934]:     return await self._protocol.query(query, timeout)
Sep 24 21:46:30 matrix.xxxxxx.xxx matrix-beeper-linkedin[3303934]:   File "asyncpg/protocol/protocol.pyx", line 338, in query
Sep 24 21:46:30 matrix.xxxxxx.xxx matrix-beeper-linkedin[3303934]: asyncpg.exceptions.UndefinedObjectError: type "string" does not exist
Sep 24 21:46:30 matrix.xxxxxx.xxx systemd[1]: matrix-beeper-linkedin.service: Main process exited, code=exited, status=25/n/a
Sep 24 21:46:30 matrix.xxxxxx.xxx systemd[1]: matrix-beeper-linkedin.service: Failed with result 'exit-code'.
```

**Comment by sumnerevans** [comment]
I think I actually fixed it finally in https://github.com/beeper/linkedin/commit/2cae15ee08e64bdba876f33d31404c04bde29823

**Comment by nebocamin** [comment]
yes!, that was it. thank you.
