### ISSUE TITLE
Unable to complete Matrix Server installation with Ansible

### ISSUE THREAD

**Issue by lucideds** [spantaleev/matrix-docker-ansible-deploy#3227]
**Playbook Configuration**:

My `vars.yml` file looks like this:

```yaml
matrix_domain: lucideds.xyz
matrix_homeserver_implementation: synapse
matrix_homeserver_generic_secret_key: "<password>"
matrix_playbook_reverse_proxy_type: playbook-managed-traefik
devture_traefik_config_certificatesResolvers_acme_email: ""
```

**Matrix Server:**
 - OS: Ubuntu LTS 22.04.4
 - Architecture arm64

**Ansible:**
Ansible Version: 2.16.4

**Problem description**:
something to do with docker keys, I have no clue on how to fix it.
```bash
The full traceback is:
Traceback (most recent call last):
  File "<stdin>", line 107, in <module>
  File "<stdin>", line 99, in _ansiballz_main
  File "<stdin>", line 47, in invoke_module
  File "/usr/lib/python3.10/runpy.py", line 224, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.10/runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_apt_repository_payload_xtyfc9c7/ansible_apt_repository_payload.zip/ansible/modules/apt_repository.py", line 765, in <module>
  File "/tmp/ansible_apt_repository_payload_xtyfc9c7/ansible_apt_repository_payload.zip/ansible/modules/apt_repository.py", line 742, in main
  File "/usr/lib/python3/dist-packages/apt/cache.py", line 152, in __init__
    self.open(progress)
  File "/usr/lib/python3/dist-packages/apt/cache.py", line 214, in open
    self._cache = apt_pkg.Cache(progress)
apt_pkg.Error: E:Conflicting values set for option Signed-By regarding source https://download.docker.com/linux/ubuntu/ jammy: /etc/apt/keyrings/docker.asc != /etc/apt/trusted.gpg.d/docker.asc, E:The list of sources could not be read.
fatal: [matrix.lucideds.xyz]: FAILED! => changed=false
  module_stderr: |-
    Traceback (most recent call last):
      File "<stdin>", line 107, in <module>
      File "<stdin>", line 99, in _ansiballz_main
      File "<stdin>", line 47, in invoke_module
      File "/usr/lib/python3.10/runpy.py", line 224, in run_module
        return _run_module_code(code, init_globals, run_name, mod_spec)
      File "/usr/lib/python3.10/runpy.py", line 96, in _run_module_code
        _run_code(code, mod_globals, init_globals,
      File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
        exec(code, run_globals)
      File "/tmp/ansible_apt_repository_payload_xtyfc9c7/ansible_apt_repository_payload.zip/ansible/modules/apt_repository.py", line 765, in <module>
      File "/tmp/ansible_apt_repository_payload_xtyfc9c7/ansible_apt_repository_payload.zip/ansible/modules/apt_repository.py", line 742, in main
      File "/usr/lib/python3/dist-packages/apt/cache.py", line 152, in __init__
        self.open(progress)
      File "/usr/lib/python3/dist-packages/apt/cache.py", line 214, in open
        self._cache = apt_pkg.Cache(progress)
    apt_pkg.Error: E:Conflicting values set for option Signed-By regarding source https://download.docker.com/linux/ubuntu/ jammy: /etc/apt/keyrings/docker.asc != /etc/apt/trusted.gpg.d/docker.asc, E:The list of sources could not be read.
  module_stdout: ''
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
  rc: 1
```
**Client (please complete the following information):**
Client not yet used.

**Additional context**
Using docker from the apt repository and I am using a rasberry pi 5, 4GB

**Comment by spantaleev** [comment]
Delete all Docker-related repository files from `/etc/apt/source.d/`.

Some likely have a `Signed-By` definition, while others do not, causing a conflict.

Once deleted, the playbook will recreate a repository file correctly (with `Signed-By`).
