### ISSUE TITLE
heisenbridge fails to start on the first try

### ISSUE THREAD

**Issue by CyberShadow** [spantaleev/matrix-docker-ansible-deploy#3448]
**Describe the bug**

When starting heisenbridge, the playbook can produce:

```
skipping: [matrix.cy.md] => (item=matrix-go-skype-bridge.service) 
failed: [matrix.cy.md] (item=matrix-heisenbridge.service) => changed=false 
  ansible_loop_var: item
  item: matrix-heisenbridge.service
  msg: matrix-heisenbridge.service was not detected to be running. It's possible that there's a configuration problem or another service on your server interferes with it (uses the same ports, etc.). Try running `systemctl status matrix-heisenbridge.service` and `journalctl -fu matrix-heisenbridge.service` on the server to investigate. If you're on a slow or overloaded server, it may be that services take a longer time to start and that this error is a false-positive. You can consider raising the value of the `devture_systemd_service_manager_up_verification_delay_seconds` variable. See `/home/vladimir/work/matrix/matrix-docker-ansible-deploy/roles/galaxy/systemd_service_manager/defaults/main.yml` for more details about that.
```

Increasing `devture_systemd_service_manager_up_verification_delay_seconds` does work around this problem, but not for the reason advertised.

Looking at the service's logs reveals:

```
Jul 27 07:31:18 matrix systemd[1]: Starting a bouncer-style Matrix IRC bridge...
Jul 27 07:31:18 matrix matrix-heisenbridge[123791]: Error response from daemon: No such container: matrix-heisenbridge
Jul 27 07:31:18 matrix matrix-heisenbridge[123802]: Error: No such container: matrix-heisenbridge
Jul 27 07:31:18 matrix matrix-heisenbridge[123813]: 5562f8f2de661daeac5fcc28aa52dc4b30edf837e0dc864d2496e38838ebba58
Jul 27 07:31:18 matrix systemd[1]: Started a bouncer-style Matrix IRC bridge.
Jul 27 07:31:19 matrix matrix-heisenbridge[123835]: Heisenbridge v0.0.0
Jul 27 07:31:19 matrix matrix-heisenbridge[123835]: ERROR:root:Unexpected failure when registering appservice user.
Jul 27 07:31:19 matrix matrix-heisenbridge[123835]: Traceback (most recent call last):
Jul 27 07:31:19 matrix matrix-heisenbridge[123835]:   File "/opt/heisenbridge/heisenbridge/__main__.py", line 505, in run
Jul 27 07:31:19 matrix matrix-heisenbridge[123835]:     await self.api.request(
Jul 27 07:31:19 matrix matrix-heisenbridge[123835]:   File "/usr/lib/python3.10/site-packages/mautrix/api.py", line 415, in request
Jul 27 07:31:19 matrix matrix-heisenbridge[123835]:     resp_data, resp = await self._send(
Jul 27 07:31:19 matrix matrix-heisenbridge[123835]:   File "/usr/lib/python3.10/site-packages/mautrix/api.py", line 265, in _send
Jul 27 07:31:19 matrix matrix-heisenbridge[123835]:     raise make_request_error(
Jul 27 07:31:19 matrix matrix-heisenbridge[123835]: mautrix.errors.request.MatrixUnknownRequestError: 404: 404 page not found
Jul 27 07:31:19 matrix matrix-heisenbridge[123835]: ERROR:asyncio:Unclosed client session
Jul 27 07:31:19 matrix matrix-heisenbridge[123835]: client_session: <aiohttp.client.ClientSession object at 0x7f3d36f30dc0>
Jul 27 07:31:19 matrix matrix-heisenbridge[123835]: ERROR:asyncio:Unclosed connector
Jul 27 07:31:19 matrix matrix-heisenbridge[123835]: connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7f3d36f193c0>, 70186.564140677)]']
Jul 27 07:31:19 matrix matrix-heisenbridge[123835]: connector: <aiohttp.connector.TCPConnector object at 0x7f3d36f30c40>
Jul 27 07:31:19 matrix systemd[1]: matrix-heisenbridge.service: Main process exited, code=exited, status=1/FAILURE
Jul 27 07:31:19 matrix systemd[1]: matrix-heisenbridge.service: Failed with result 'exit-code'.
```

It looks like the playbook may be starting this service too early, before the Matrix server is ready to talk to it.

However, since it is configured to be `Restart=always` and `RestartSec=30`, the second retry works.

**To Reproduce**
Not sure what exactly caused me to hit it.

**Expected behavior**
Service should start on the first try.

**Matrix Server:**
 - OS: Ubuntu 22.04
 - Architecture x86_64

**Additional context**

**Comment by spantaleev** [comment]
Closing this as part of a backlog review.

This is a first-start race: on the very first installation, heisenbridge can probe the homeserver before it is ready and exit, and systemd's Restart=always brings it up seconds later. The failure is transient and self-healing, and the error message itself points at the wait-time knob for tuning the startup ordering.

Making heisenbridge itself tolerate a not-yet-ready homeserver (retrying instead of exiting) would be the proper fix, but that belongs upstream, and upstream heisenbridge is not seeing much development these days. On the playbook side, a generic homeserver-readiness gate for all appservices would be an architectural project that nobody has asked for since this was filed, so we are not planning it.

If the failure loop ever turns out not to self-heal on a current setup, please open a fresh issue with the service logs.
