### ISSUE TITLE
matrix-bot-draupnir is still unable to start

### ISSUE THREAD

**Issue by dementeb** [spantaleev/matrix-docker-ansible-deploy#3463]
The fix https://github.com/spantaleev/matrix-docker-ansible-deploy/commit/cb7726f4a8b3082e1fdab8949c60f07f5b6bdee7 doesn't resolve this problem.
Sorry if this is a duplicate, but this is just really important for my setup, and the old report is closed as fixed.

**To Reproduce**
My `vars.yml` file looks like this:

```yaml

matrix_synapse_encryption_enabled_by_default_for_room_type: all
matrix_pantalaimon_enabled: true
matrix_bot_draupnir_enabled: true
matrix_bot_draupnir_pantalaimon_use: true
matrix_bot_draupnir_pantalaimon_username: "bot.name"
matrix_bot_draupnir_pantalaimon_password: "strongpass"
matrix_bot_draupnir_management_room: "!ididididid:domain.com"
matrix_bot_draupnir_configuration_extension_yaml: |
  recordIgnoredInvites: true
  pollReports: true
```

**Matrix Server:**
 - OS: [Ubuntu 22.04]
 - Architecture [amd64]

**Additional context**
matrix-bot-draupnir systemd service terminates with an error:

```
Jul 31 13:17:15 matrix matrix-bot-draupnir[1098416]: Failed to setup mjolnir from the config /data: Error: undefined: undefined
Jul 31 13:17:15 matrix matrix-bot-draupnir[1098416]: node:internal/process/promises:289
Jul 31 13:17:15 matrix matrix-bot-draupnir[1098416]:             triggerUncaughtException(err, true /* fromPromise */);
Jul 31 13:17:15 matrix matrix-bot-draupnir[1098416]:             ^
Jul 31 13:17:15 matrix matrix-bot-draupnir[1098416]: MatrixError: Error during MatrixClient request POST /_matrix/client/v3/login: 500 Internal Server Error -- "Cannot connect to host >
Jul 31 13:17:15 matrix matrix-bot-draupnir[1098416]:     at /mjolnir/utils.js:278:21
Jul 31 13:17:15 matrix matrix-bot-draupnir[1098416]:     at result (/mjolnir/utils.js:397:25)
Jul 31 13:17:15 matrix matrix-bot-draupnir[1098416]:     at new Promise (<anonymous>)
Jul 31 13:17:15 matrix matrix-bot-draupnir[1098416]:     at /mjolnir/utils.js:396:40
Jul 31 13:17:15 matrix matrix-bot-draupnir[1098416]:     at respIsBuffer (/node_modules/matrix-bot-sdk/lib/http.js:66:38)
Jul 31 13:17:15 matrix matrix-bot-draupnir[1098416]:     at new Promise (<anonymous>)
Jul 31 13:17:15 matrix matrix-bot-draupnir[1098416]:     at doHttpRequest (/node_modules/matrix-bot-sdk/lib/http.js:65:41)
Jul 31 13:17:15 matrix matrix-bot-draupnir[1098416]:     at MatrixClient.doRequest (/node_modules/matrix-bot-sdk/lib/MatrixClient.js:1785:41)
Jul 31 13:17:15 matrix matrix-bot-draupnir[1098416]:     at descriptor.value (/node_modules/matrix-bot-sdk/lib/metrics/decorators.js:19:53)
Jul 31 13:17:15 matrix matrix-bot-draupnir[1098416]:     at MatrixAuth.passwordLogin (/node_modules/matrix-bot-sdk/lib/MatrixAuth.js:113:60) {
Jul 31 13:17:15 matrix matrix-bot-draupnir[1098416]:   body: 'Cannot connect to host matrix-traefik:8008 ssl:False [Name or service not known]',
Jul 31 13:17:15 matrix matrix-bot-draupnir[1098416]:   statusCode: 500,
Jul 31 13:17:15 matrix matrix-bot-draupnir[1098416]:   errcode: undefined,
Jul 31 13:17:15 matrix matrix-bot-draupnir[1098416]:   error: undefined,
Jul 31 13:17:15 matrix matrix-bot-draupnir[1098416]:   retryAfterMs: undefined
Jul 31 13:17:15 matrix matrix-bot-draupnir[1098416]: }
Jul 31 13:17:15 matrix matrix-bot-draupnir[1098416]: Node.js v20.11.1
Jul 22 17:13:35 matrix systemd[1]: matrix-bot-draupnir.service: Main process exited, code=exited, status=1/FAILURE
Jul 22 17:13:35 matrix systemd[1]: matrix-bot-draupnir.service: Failed with result 'exit-code'.
```

**Comment by FSG-Cat** [comment]
Well this seems to me to be another occurance of recent troubles with E2EE and Draupnir. Draupnir 2.0-beta.4 i think or 5 fixes native E2EE race condition that made it not work at all. 

https://the-draupnir-project.github.io/draupnir-documentation/bot/encryption
https://the-draupnir-project.github.io/draupnir-documentation/shared/dogfood

These links should shine a light on the problems with Pantal and Draupnir. Pantal has known issues and at times stuff like this happens.

Anyways if this situation persists your welcome to the Draupnir room for questions. Like i know that for some users Pantal and Draupnir happily co exist with the known problems.

**Comment by spantaleev** [comment]
Closing this as part of a backlog cleanup, since the setup it describes no longer matches the current playbook. The report was made against Draupnir 1.x running through Pantalaimon, and the log shows Pantalaimon itself failing to reach the homeserver. Since then, Draupnir gained native E2EE support (available in the playbook via `matrix_bot_draupnir_config_experimentalRustCrypto`), the playbook now ships Draupnir v3.x, and running Draupnir through Pantalaimon is discouraged by upstream (the playbook warns about it, because it breaks workflows that rely on answering prompts with reactions). The migration away from Pantalaimon is described in the Draupnir docs page of the playbook. There has also been no response to the needs-info request. If you are still on a Pantalaimon-based setup, please switch to the native E2EE path; if the problem reappears on a current playbook setup, feel free to open a new issue with fresh logs and we will take a look.
