### ISSUE TITLE
Hookshot configuration widget fails with odd error

### ISSUE THREAD

**Issue by aine-etke** [spantaleev/matrix-docker-ansible-deploy#3550]
**Describe the bug**

Hookshot configuration widget fails with the following error in UI:

![image](https://github.com/user-attachments/assets/ae6032b9-2ba1-48dd-8aa3-65c2a8b218c4)

And the following errors in logs (`DOMAIN` is matrix server's base domain):

```
WARN 12:01:44:809 [ProvisioningApi] Failed to fetch the server URL for DOMAIN ApiError: API error M_AS_BAD_OPENID: Server is disallowed
    at BridgeWidgetApi.checkIpBlacklist (/usr/bin/matrix-hookshot/node_modules/matrix-appservice-bridge/lib/provisioning/api.js:255:19)
    at async BridgeWidgetApi.postExchangeOpenId (/usr/bin/matrix-hookshot/node_modules/matrix-appservice-bridge/lib/provisioning/api.js:279:17) {
  error: 'Server is disallowed',
  errcode: 'M_AS_BAD_OPENID',
  statusCode: 500,
  additionalContent: {}
}
ERROR 12:01:44:809 [ProvisioningApi] ApiError: API error M_AS_BAD_OPENID: Could not identify server url
    at BridgeWidgetApi.postExchangeOpenId (/usr/bin/matrix-hookshot/node_modules/matrix-appservice-bridge/lib/provisioning/api.js:284:19) {
  error: 'Could not identify server url',
  errcode: 'M_AS_BAD_OPENID',
  statusCode: 500,
  additionalContent: {}
}
```

**To Reproduce**
My `vars.yml` file looks like this:

```yaml
devture_postgres_connection_password: REDACTED
matrix_domain: DOMAIN
matrix_admin: REDACTED
devture_traefik_config_certificatesResolvers_acme_email: REDDACTED
matrix_static_files_file_matrix_support_enabled: yes
matrix_static_files_file_matrix_support_property_m_contacts:
  - matrix_id: REDACTED
    email_address: REDACTED
    role: m.role.admin
matrix_user_creator_users_additional:
 - username: READACTED
   initial_password: REDACTED
   initial_type: admin
matrix_synapse_ext_password_provider_shared_secret_auth_enabled: yes
matrix_synapse_ext_password_provider_shared_secret_auth_shared_secret: REDACTED
matrix_synapse_macaroon_secret_key: READACTED
matrix_synapse_password_config_pepper: READACTED
matrix_coturn_turn_static_auth_secret: REDACTED
matrix_homeserver_generic_secret_key: "{{ matrix_synapse_macaroon_secret_key }}"
matrix_static_files_container_labels_base_domain_enabled: yes
exim_relay_dkim_privkey_contents: REDACTED
matrix_client_element_enabled: yes
matrix_synapse_admin_enabled: yes
matrix_bot_postmoogle_enabled: yes
matrix_bot_postmoogle_password: READACTED
matrix_bot_postmoogle_data_secret: REDACTED
matrix_mautrix_meta_messenger_enabled: yes
matrix_mautrix_gmessages_enabled: yes
matrix_mautrix_googlechat_enabled: yes
matrix_mautrix_meta_instagram_enabled: yes
matrix_beeper_linkedin_enabled: yes
matrix_mautrix_slack_enabled: yes
matrix_hookshot_enabled: yes
```

1. `!hookshot setup-widget`
2. Try to open the new widget

**Expected behavior**

Widget is shown

**Matrix Server:**
 - OS: Ubuntu 22.04.5 LTS
 - Architecture: amd64

**Additional Context**

Freshly installed server, hookshot v5.4.1

**Comment by spantaleev** [comment]
Seems like the error is raised by [matrix-appservice-bridge](https://github.com/matrix-org/matrix-appservice-bridge) here: https://github.com/matrix-org/matrix-appservice-bridge/blob/09980903eb24993211771acf24a7d75d194b5144/src/provisioning/api.ts#L356-L382

It seems like the logic ultimately intends to call the `/_matrix/federation/v1/openid/userinfo` endpoint, which is a federation endpoint.

I'm not sure what the resolving logic (`this.wellknown.resolveMatrixServer(server)`) does, but.. given that `this.checkIpBlacklist(url)` fails with "Server is disallowed" makes me think that:

- **either** the resolving logic **resulted in a local IP address** which is not whitelisted in `DefaultDisallowedIpRanges` [here](https://github.com/matrix-org/matrix-appservice-bridge/blob/09980903eb24993211771acf24a7d75d194b5144/src/provisioning/api.ts#L17-L37). This may be because a lookup for `matrix.DOMAIN` for the given host resulted in a local IP address (possibly a container IP address) due to some DNS resolution problem or "feature" that makes `matrix.DOMAIN` resolve locally
- **or** no such DNS lookup is done and Hookshot passes the `bridge.url` configuration value (coming from `matrix_hookshot_homeserver_address`). In most configurations, this goes to `http://matrix-traefik:8008` (the Matrix internal Client-Server API). Yes, this is an internal/local IP address.. Even if it's whitelisted, it won't be of much use, because it only serves the Client-Server API there, not federation APIs.

Checking `this.wellknown.resolveMatrixServer(server)`, it seems to be [MatrixHostResolver]([here](https://github.com/matrix-org/matrix-appservice-bridge/blob/09980903eb24993211771acf24a7d75d194b5144/src/utils/matrix-host-resolver.ts#L41))::[resolveMatrixServer](https://github.com/matrix-org/matrix-appservice-bridge/blob/09980903eb24993211771acf24a7d75d194b5144/src/utils/matrix-host-resolver.ts#L299-L341). Looking at this class, it does seem like **it's only doing well-known lookups and DNS resolution**, not looking at configuration (like `bridge.url` which is potentially pointed to an in-container address).

So.. **it seems like the well-known lookup and DNS resolution indeed resulted in a local (possibly container) IP**.

Debugging can continue with figuring out why `nslookup matrix.example.com` in the Hookshot container resulted in a local IP address.

One possibility may be that `/etc/resolv.conf` on the host defines a `matrix.example.com` entry and points it to `127.0.0.1` or something, and then.. Docker containers (which go through Docker's internal DNS server) provide this result as-is.

**Comment by timmydmsdy** [comment]
So I have been running into the same exact error as well. Some troubleshooting showed the the container was picking up the listings in my /etc/hosts which mapped my home server domain name to 127.0.1.1. 

To test, I commented that line out of my host file and then restarted the container. It now resolves my home server domain correctly, but ultimately produces the same error, albeit with more error information this time.

here is the new error I get, I have changed my hostname to example.com in the logs.
```

WARN 20:49:01:279 [ProvisioningApi] Failed to exchange the token for example.com [AxiosError: Request failed with status code 404] {
  code: 'ERR_BAD_REQUEST',
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [Function: httpAdapter],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    env: { FormData: [Function] },
    validateStatus: [Function: validateStatus],
    headers: {
      Accept: 'application/json, text/plain, */*',
      Host: 'matrix.example.com:443',
      'User-Agent': 'axios/0.27.2'
    },
    params: { access_token: 'nVBENHhwUSUhInBhbumBAgKj' },
    method: 'get',
    url: 'https://matrix.example.com/_matrix/federation/v1/openid/userinfo',
    data: undefined
  },
  request: <ref *1> ClientRequest {
    _events: [Object: null prototype] {
      abort: [Function (anonymous)],
      aborted: [Function (anonymous)],
      connect: [Function (anonymous)],
      error: [Function (anonymous)],
      socket: [Function (anonymous)],
      timeout: [Function (anonymous)],
      finish: [Function: requestOnFinish]
    },
    _eventsCount: 7,
    _maxListeners: undefined,
    outputData: [],
    outputSize: 0,
    writable: true,
    destroyed: true,
    _last: true,
    chunkedEncoding: false,
    shouldKeepAlive: true,
    maxRequestsOnConnectionReached: false,
    _defaultKeepAlive: true,
    useChunkedEncodingByDefault: false,
    sendDate: false,
    _removedConnection: false,
    _removedContLen: false,
    _removedTE: false,
    strictContentLength: false,
    _contentLength: 0,
    _hasBody: true,
    _trailer: '',
    finished: true,
    _headerSent: true,
    _closed: true,
    _header: 'GET /_matrix/federation/v1/openid/userinfo?access_token=nVBENHhwUSUhInBhbumBAgKj HTTP/1.1\r\n' +
      'Accept: application/json, text/plain, */*\r\n' +
      'Host: matrix.example.com:443\r\n' +
      'User-Agent: axios/0.27.2\r\n' +
      'Connection: keep-alive\r\n' +
      '\r\n',
    _keepAliveTimeout: 0,
    _onPendingData: [Function: nop],
    agent: Agent {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      defaultPort: 443,
      protocol: 'https:',
      options: [Object: null prototype],
      requests: [Object: null prototype] {},
      sockets: [Object: null prototype] {},
      freeSockets: [Object: null prototype],
      keepAliveMsecs: 1000,
      keepAlive: true,
      maxSockets: Infinity,
      maxFreeSockets: 256,
      scheduling: 'lifo',
      maxTotalSockets: Infinity,
      totalSocketCount: 1,
      maxCachedSessions: 100,
      _sessionCache: [Object],
      [Symbol(shapeMode)]: false,
      [Symbol(kCapture)]: false
    },
    socketPath: undefined,
    method: 'GET',
    maxHeaderSize: undefined,
    insecureHTTPParser: undefined,
    joinDuplicateHeaders: undefined,
    path: '/_matrix/federation/v1/openid/userinfo?access_token=nVBENHhwUSUhInBhbumBAgKj',
    _ended: true,
    res: IncomingMessage {
      _events: [Object],
      _readableState: [ReadableState],
      _maxListeners: undefined,
      socket: null,
      httpVersionMajor: 1,
      httpVersionMinor: 1,
      httpVersion: '1.1',
      complete: true,
      rawHeaders: [Array],
      rawTrailers: [],
      joinDuplicateHeaders: undefined,
      aborted: false,
      upgrade: false,
      url: '',
      method: null,
      statusCode: 404,
      statusMessage: 'Not Found',
      client: [TLSSocket],
      _consuming: true,
      _dumped: false,
      req: [Circular *1],
      _eventsCount: 4,
      responseUrl: 'https://matrix.example.com/_matrix/federation/v1/openid/userinfo?access_token=nVBENHhwUSUhInBhbumBAgKj',
      redirects: [],
      [Symbol(shapeMode)]: true,
      [Symbol(kCapture)]: false,
      [Symbol(kHeaders)]: [Object],
      [Symbol(kHeadersCount)]: 20,
      [Symbol(kTrailers)]: null,
      [Symbol(kTrailersCount)]: 0
    },
    aborted: false,
    timeoutCb: null,
    upgradeOrConnect: false,
    parser: null,
    maxHeadersCount: null,
    reusedSocket: false,
    host: 'matrix.example.com',
    protocol: 'https:',
    _redirectable: Writable {
      _events: [Object],
      _writableState: [WritableState],
      _maxListeners: undefined,
      _options: [Object],
      _ended: true,
      _ending: true,
      _redirectCount: 0,
      _redirects: [],
      _requestBodyLength: 0,
      _requestBodyBuffers: [],
      _eventsCount: 3,
      _onNativeResponse: [Function (anonymous)],
      _currentRequest: [Circular *1],
      _currentUrl: 'https://matrix.example.com/_matrix/federation/v1/openid/userinfo?access_token=nVBENHhwUSUhInBhbumBAgKj',
      [Symbol(shapeMode)]: true,
      [Symbol(kCapture)]: false
    },
    [Symbol(shapeMode)]: false,
    [Symbol(kCapture)]: false,
    [Symbol(kBytesWritten)]: 0,
    [Symbol(kNeedDrain)]: false,
    [Symbol(corked)]: 0,
    [Symbol(kChunkedBuffer)]: [],
    [Symbol(kChunkedLength)]: 0,
    [Symbol(kSocket)]: TLSSocket {
      _tlsOptions: [Object],
      _secureEstablished: true,
      _securePending: false,
      _newSessionPending: false,
      _controlReleased: true,
      secureConnecting: false,
      _SNICallback: null,
      servername: 'matrix.example.com',
      alpnProtocol: false,
      authorized: true,
      authorizationError: null,
      encrypted: true,
      _events: [Object: null prototype],
      _eventsCount: 9,
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: 'matrix.example.com',
      _closeAfterHandlingError: false,
      _readableState: [ReadableState],
      _writableState: [WritableState],
      allowHalfOpen: false,
      _maxListeners: undefined,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: undefined,
      _server: null,
      ssl: [TLSWrap],
      _requestCert: true,
      _rejectUnauthorized: true,
      timeout: 5000,
      parser: null,
      _httpMessage: null,
      [Symbol(alpncallback)]: null,
      [Symbol(res)]: [TLSWrap],
      [Symbol(verified)]: true,
      [Symbol(pendingSession)]: null,
      [Symbol(async_id_symbol)]: -1,
      [Symbol(kHandle)]: [TLSWrap],
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: Timeout {
        _idleTimeout: 5000,
        _idlePrev: [TimersList],
        _idleNext: [TimersList],
        _idleStart: 637143,
        _onTimeout: [Function: bound ],
        _timerArgs: undefined,
        _repeat: null,
        _destroyed: false,
        [Symbol(refed)]: false,
        [Symbol(kHasPrimitive)]: false,
        [Symbol(asyncId)]: 2493,
        [Symbol(triggerId)]: 2491,
        [Symbol(kAsyncContextFrame)]: undefined
      },
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(shapeMode)]: true,
      [Symbol(kCapture)]: false,
      [Symbol(kSetNoDelay)]: false,
      [Symbol(kSetKeepAlive)]: true,
      [Symbol(kSetKeepAliveInitialDelay)]: 1,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(connect-options)]: [Object]
    },
    [Symbol(kOutHeaders)]: [Object: null prototype] {
      accept: [Array],
      host: [Array],
      'user-agent': [Array]
    },
    [Symbol(errored)]: null,
    [Symbol(kHighWaterMark)]: 65536,
    [Symbol(kRejectNonStandardBodyWrites)]: false,
    [Symbol(kUniqueHeaders)]: null
  },
  response: {
    status: 404,
    statusText: 'Not Found',
    headers: {
      'access-control-allow-headers': 'X-Requested-With, Content-Type, Authorization, Date',
      'access-control-allow-methods': 'GET, HEAD, POST, PUT, DELETE, OPTIONS',
      'access-control-allow-origin': '*',
      'access-control-expose-headers': 'Synapse-Trace-Id, Server',
      'alt-svc': 'h3=":443"; ma=2592000',
      'cache-control': 'no-cache, no-store, must-revalidate',
      'content-type': 'application/json',
      date: 'Thu, 03 Apr 2025 20:49:01 GMT',
      server: 'Synapse/1.127.1',
      'transfer-encoding': 'chunked'
    },
    config: {
      transitional: [Object],
      adapter: [Function: httpAdapter],
      transformRequest: [Array],
      transformResponse: [Array],
      timeout: 0,
      xsrfCookieName: 'XSRF-TOKEN',
      xsrfHeaderName: 'X-XSRF-TOKEN',
      maxContentLength: -1,
      maxBodyLength: -1,
      env: [Object],
      validateStatus: [Function: validateStatus],
      headers: [Object],
      params: [Object],
      method: 'get',
      url: 'https://matrix.example.com/_matrix/federation/v1/openid/userinfo',
      data: undefined
    },
    request: <ref *1> ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: true,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: true,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      strictContentLength: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: true,
      _header: 'GET /_matrix/federation/v1/openid/userinfo?access_token=nVBENHhwUSUhInBhbumBAgKj HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'Host: matrix.example.com:443\r\n' +
        'User-Agent: axios/0.27.2\r\n' +
        'Connection: keep-alive\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      joinDuplicateHeaders: undefined,
      path: '/_matrix/federation/v1/openid/userinfo?access_token=nVBENHhwUSUhInBhbumBAgKj',
      _ended: true,
      res: [IncomingMessage],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'matrix.example.com',
      protocol: 'https:',
      _redirectable: [Writable],
      [Symbol(shapeMode)]: false,
      [Symbol(kCapture)]: false,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kChunkedBuffer)]: [],
      [Symbol(kChunkedLength)]: 0,
      [Symbol(kSocket)]: [TLSSocket],
      [Symbol(kOutHeaders)]: [Object: null prototype],
      [Symbol(errored)]: null,
      [Symbol(kHighWaterMark)]: 65536,
      [Symbol(kRejectNonStandardBodyWrites)]: false,
      [Symbol(kUniqueHeaders)]: null
    },
    data: { errcode: 'M_UNRECOGNIZED', error: 'Unrecognized request' }
  }
}
ERROR 20:49:01:280 [ProvisioningApi] ApiError: API error M_AS_BAD_OPENID: Failed to exchange token
    at BridgeWidgetApi.postExchangeOpenId (/usr/bin/matrix-hookshot/node_modules/matrix-appservice-bridge/lib/provisioning/api.js:321:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5) {
  error: 'Failed to exchange token',
  errcode: 'M_AS_BAD_OPENID',
  statusCode: 500,
  additionalContent: {}
}
```

**Comment by Sulfiore** [comment]
@aine-etke Did you manage to solve the issue ? I have exactly the same problem with my instance

**Comment by aine-etke** [comment]
No, the hookshot was replaced on that instance because it lacked some other features

But take a look at the Slavi's suggestion - /etc/hosts and /etc/resolv.conf definitely could be the culprit (confirmed for other components and use-cases)

**Comment by Sulfiore** [comment]
I managed to fix it by adding the `disallowedIpRange` configuration and removing the ip range of my synapse server (in my case 10.0.0.0/8)

**Comment by spantaleev** [comment]
Closing this one, as it has run its course and there is nothing left to act on in the playbook.

The root cause is upstream: matrix-appservice-bridge's provisioning API blocks OpenID exchange when the homeserver's federation address resolves to a private/local IP (its default disallowed IP ranges). Whether that happens depends on the server's DNS setup, so it is environment-specific rather than a defect in the playbook.

The debugging info requested back in November 2024 (DNS resolution from inside the Hookshot container) was never gathered, and Hookshot was since replaced on the affected instance, so this cannot be investigated further.

For anyone else hitting this: as confirmed later in this thread, you can resolve it by overriding the disallowed IP ranges via the existing `matrix_hookshot_widgets_disallowedIpRanges` variable in the playbook (see `roles/custom/matrix-bridge-hookshot/defaults/main.yml` for details), excluding the private range your homeserver resolves to. Be aware that loosening these ranges has security implications, so only allow what you need.

If someone runs into this on a current setup and can provide the container-side DNS resolution details, feel free to comment and we can reopen.
