### ISSUE TITLE
Unable to deploy hookshot bridge with MAS enabled

### ISSUE THREAD

**Issue by wjbeckett** [spantaleev/matrix-docker-ansible-deploy#3658]
**Describe the bug**
With MAS enabled, hookshot cannot be deployed due to Invalid login type.

**Additional context**
```
Oct 22 06:57:24 wb-matrix systemd[1]: matrix-hookshot.service: Scheduled restart job, restart counter is at 8.
Oct 22 06:57:24 wb-matrix systemd[1]: Starting matrix-hookshot.service - A bridge between Matrix and multiple project management services, such as GitHub, GitLab and JIRA....
Oct 22 06:57:24 wb-matrix matrix-hookshot[37840]: Error response from daemon: No such container: matrix-hookshot
Oct 22 06:57:24 wb-matrix matrix-hookshot[37847]: Error response from daemon: No such container: matrix-hookshot
Oct 22 06:57:24 wb-matrix matrix-hookshot[37856]: c443d112c76c9629f3f42b0884970e1d951d27faf190874cd0a3da750e9eebdd
Oct 22 06:57:24 wb-matrix systemd[1]: Started matrix-hookshot.service - A bridge between Matrix and multiple project management services, such as GitHub, GitLab and JIRA..
Oct 22 06:57:26 wb-matrix matrix-hookshot[37882]: WARN 06:57:26:896 [Config] You have not configured any permissions for the bridge, which by default means all users on beckettnet.org have admin levels of control. Please adjust your config.
Oct 22 06:57:26 wb-matrix matrix-hookshot[37882]: WARN 06:57:26:898 [Config]
Oct 22 06:57:26 wb-matrix matrix-hookshot[37882]: You have enabled encryption support in the bridge. This feature is HIGHLY EXPERIMENTAL AND SUBJECT TO CHANGE.
Oct 22 06:57:26 wb-matrix matrix-hookshot[37882]: For more details, see https://github.com/matrix-org/matrix-hookshot/issues/594.
Oct 22 06:57:26 wb-matrix matrix-hookshot[37882]:
Oct 22 06:57:26 wb-matrix matrix-hookshot[37882]: INFO 06:57:26:929 [ListenerService] Listening on http://0.0.0.0:9000 for webhooks
Oct 22 06:57:26 wb-matrix matrix-hookshot[37882]: INFO 06:57:26:930 [ListenerService] Listening on http://0.0.0.0:9003 for widgets
Oct 22 06:57:27 wb-matrix matrix-hookshot[37882]: ERROR 06:57:27:037 [MatrixHttpClient] (REQ-5) { errcode: 'M_UNRECOGNIZED', error: 'Invalid login type' }
Oct 22 06:57:27 wb-matrix matrix-hookshot[37882]: ERROR 06:57:27:039 [Appservice] Failed to set up crypto on intent @hookshot:beckettnet.org MatrixError: M_UNRECOGNIZED: Invalid login type
Oct 22 06:57:27 wb-matrix matrix-hookshot[37882]:     at doHttpRequest (/usr/bin/matrix-hookshot/node_modules/matrix-bot-sdk/lib/http.js:95:15)
Oct 22 06:57:27 wb-matrix matrix-hookshot[37882]:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Oct 22 06:57:27 wb-matrix matrix-hookshot[37882]:     at async descriptor.value (/usr/bin/matrix-hookshot/node_modules/matrix-bot-sdk/lib/metrics/decorators.js:19:32)
Oct 22 06:57:27 wb-matrix matrix-hookshot[37882]:     at async /usr/bin/matrix-hookshot/node_modules/matrix-bot-sdk/lib/appservice/Intent.js:166:41 {
Oct 22 06:57:27 wb-matrix matrix-hookshot[37882]:   body: { errcode: 'M_UNRECOGNIZED', error: 'Invalid login type' },
Oct 22 06:57:27 wb-matrix matrix-hookshot[37882]:   statusCode: 400,
Oct 22 06:57:27 wb-matrix matrix-hookshot[37882]:   errcode: 'M_UNRECOGNIZED',
Oct 22 06:57:27 wb-matrix matrix-hookshot[37882]:   error: 'Invalid login type',
Oct 22 06:57:27 wb-matrix matrix-hookshot[37882]:   retryAfterMs: undefined
Oct 22 06:57:27 wb-matrix matrix-hookshot[37882]: }
Oct 22 06:57:27 wb-matrix matrix-hookshot[37882]: node:internal/process/promises:289
Oct 22 06:57:27 wb-matrix matrix-hookshot[37882]:             triggerUncaughtException(err, true /* fromPromise */);
Oct 22 06:57:27 wb-matrix matrix-hookshot[37882]:             ^
Oct 22 06:57:27 wb-matrix matrix-hookshot[37882]: MatrixError: M_UNRECOGNIZED: Invalid login type
Oct 22 06:57:27 wb-matrix matrix-hookshot[37882]:     at doHttpRequest (/usr/bin/matrix-hookshot/node_modules/matrix-bot-sdk/lib/http.js:95:15)
Oct 22 06:57:27 wb-matrix matrix-hookshot[37882]:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Oct 22 06:57:27 wb-matrix matrix-hookshot[37882]:     at async descriptor.value (/usr/bin/matrix-hookshot/node_modules/matrix-bot-sdk/lib/metrics/decorators.js:19:32)
Oct 22 06:57:27 wb-matrix matrix-hookshot[37882]:     at async /usr/bin/matrix-hookshot/node_modules/matrix-bot-sdk/lib/appservice/Intent.js:166:41 {
Oct 22 06:57:27 wb-matrix matrix-hookshot[37882]:   body: { errcode: 'M_UNRECOGNIZED', error: 'Invalid login type' },
Oct 22 06:57:27 wb-matrix matrix-hookshot[37882]:   statusCode: 400,
Oct 22 06:57:27 wb-matrix matrix-hookshot[37882]:   errcode: 'M_UNRECOGNIZED',
Oct 22 06:57:27 wb-matrix matrix-hookshot[37882]:   error: 'Invalid login type',
Oct 22 06:57:27 wb-matrix matrix-hookshot[37882]:   retryAfterMs: undefined
Oct 22 06:57:27 wb-matrix matrix-hookshot[37882]: }
Oct 22 06:57:27 wb-matrix matrix-hookshot[37882]: Node.js v20.12.2
Oct 22 06:57:27 wb-matrix systemd[1]: matrix-hookshot.service: Main process exited, code=exited, status=1/FAILURE
Oct 22 06:57:27 wb-matrix systemd[1]: matrix-hookshot.service: Failed with result 'exit-code'.
```

**Comment by spantaleev** [comment]
Encrypted appservices do not work with MAS. Related to:

- https://github.com/matrix-org/matrix-spec-proposals/pull/4190
- https://github.com/element-hq/synapse/pull/17705

If you disable encryption support for this bridge (`matrix_hookshot_experimental_encryption_enabled: false`), you may have better luck.
