### ISSUE TITLE
How do I add files to matrix synapse?

### ISSUE THREAD

**Issue by hungrymonkey** [spantaleev/matrix-docker-ansible-deploy#416]
Hi Matrix Playbook community,

How do I add files to this playbook. I have been following this guide to configure SAML and keycloak and I keep hitting this error. All the files, in the guide such as `sp_config.py`, are copied manually.
https://edenmal.moe/post/2019/Matrix-Synapse-SAML2-Login/#your-matrix-synapse-homeserver-config-yaml-file

Do I need to extend the playbook?
```
Mar 23 21:55:41 ip-172-31-12-25 systemd[1]: Started Synapse server.
Mar 23 21:55:45 ip-172-31-12-25 matrix-synapse[18970]: This server is configured to use 'matrix.org' as its trusted key server via the
Mar 23 21:55:45 ip-172-31-12-25 matrix-synapse[18970]: 'trusted_key_servers' config option. 'matrix.org' is a good choice for a key
Mar 23 21:55:45 ip-172-31-12-25 matrix-synapse[18970]: server since it is long-lived, stable and trusted. However, some admins may
Mar 23 21:55:45 ip-172-31-12-25 matrix-synapse[18970]: wish to use another server for this purpose.
Mar 23 21:55:45 ip-172-31-12-25 matrix-synapse[18970]: To suppress this warning and continue using 'matrix.org', admins should set
Mar 23 21:55:45 ip-172-31-12-25 matrix-synapse[18970]: 'suppress_key_server_warning' to 'true' in homeserver.yaml.
Mar 23 21:55:45 ip-172-31-12-25 matrix-synapse[18970]: --------------------------------------------------------------------------------
Mar 23 21:55:45 ip-172-31-12-25 matrix-synapse[18970]: Traceback (most recent call last):
Mar 23 21:55:45 ip-172-31-12-25 matrix-synapse[18970]:   File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
Mar 23 21:55:45 ip-172-31-12-25 matrix-synapse[18970]:     "__main__", mod_spec)
Mar 23 21:55:45 ip-172-31-12-25 matrix-synapse[18970]:   File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
Mar 23 21:55:45 ip-172-31-12-25 matrix-synapse[18970]:     exec(code, run_globals)
Mar 23 21:55:45 ip-172-31-12-25 matrix-synapse[18970]:   File "/usr/local/lib/python3.7/site-packages/synapse/app/homeserver.py", line 651, in <module>
Mar 23 21:55:45 ip-172-31-12-25 matrix-synapse[18970]:     main()
Mar 23 21:55:45 ip-172-31-12-25 matrix-synapse[18970]:   File "/usr/local/lib/python3.7/site-packages/synapse/app/homeserver.py", line 646, in main
Mar 23 21:55:45 ip-172-31-12-25 matrix-synapse[18970]:     hs = setup(sys.argv[1:])
Mar 23 21:55:45 ip-172-31-12-25 matrix-synapse[18970]:   File "/usr/local/lib/python3.7/site-packages/synapse/app/homeserver.py", line 324, in setup
Mar 23 21:55:45 ip-172-31-12-25 matrix-synapse[18970]:     "Synapse Homeserver", config_options
Mar 23 21:55:45 ip-172-31-12-25 matrix-synapse[18970]:   File "/usr/local/lib/python3.7/site-packages/synapse/config/_base.py", line 629, in load_or_generate_config
Mar 23 21:55:45 ip-172-31-12-25 matrix-synapse[18970]:     config_dict, config_dir_path=config_dir_path, data_dir_path=data_dir_path
Mar 23 21:55:45 ip-172-31-12-25 matrix-synapse[18970]:   File "/usr/local/lib/python3.7/site-packages/synapse/config/_base.py", line 651, in parse_config_dict
Mar 23 21:55:45 ip-172-31-12-25 matrix-synapse[18970]:     data_dir_path=data_dir_path,
Mar 23 21:55:45 ip-172-31-12-25 matrix-synapse[18970]:   File "/usr/local/lib/python3.7/site-packages/synapse/config/_base.py", line 266, in invoke_all
Mar 23 21:55:45 ip-172-31-12-25 matrix-synapse[18970]:     res[name] = getattr(config, func_name)(*args, **kwargs)
Mar 23 21:55:45 ip-172-31-12-25 matrix-synapse[18970]:   File "/usr/local/lib/python3.7/site-packages/synapse/config/saml2_config.py", line 153, in read_config
Mar 23 21:55:45 ip-172-31-12-25 matrix-synapse[18970]:     mod = load_python_module(config_path)
Mar 23 21:55:45 ip-172-31-12-25 matrix-synapse[18970]:   File "/usr/local/lib/python3.7/site-packages/synapse/util/module_loader.py", line 57, in load_python_module
Mar 23 21:55:45 ip-172-31-12-25 matrix-synapse[18970]:     spec.loader.exec_module(mod)  # type: ignore
Mar 23 21:55:45 ip-172-31-12-25 matrix-synapse[18970]:   File "<frozen importlib._bootstrap_external>", line 724, in exec_module
Mar 23 21:55:45 ip-172-31-12-25 matrix-synapse[18970]:   File "<frozen importlib._bootstrap_external>", line 859, in get_code
Mar 23 21:55:45 ip-172-31-12-25 matrix-synapse[18970]:   File "<frozen importlib._bootstrap_external>", line 916, in get_data
Mar 23 21:55:45 ip-172-31-12-25 matrix-synapse[18970]: FileNotFoundError: [Errno 2] No such file or directory: '/matrix/synapse/config/sp_conf.py'
qMar 23 21:55:46 ip-172-31-12-25 systemd[1]: matrix-synapse.service: Main process exited, code=exited, status=1/FAILURE
Mar 23 21:55:46 ip-172-31-12-25 systemd[1]: matrix-synapse.service: Failed with result 'exit-code'.
```

**Comment by spantaleev** [comment]
Mounting additional files into the Synapse container is possible by using `matrix_synapse_container_additional_volumes`. Check its documentation in `roles/matrix-synapse/defaults/main.yml`.

However, If you've put `sp_conf.py` in `/matrix/synapse/config` on the host, you won't have to mount it explicitly. The `/matrix/synapse/config` directory already gets mounted to `/data` in the Synapse container`. You can then set `saml2_configconfig_path`  to something like `/data/sp_conf.py`

As for how you set `saml2_config` properly without editing the `homeserver.yaml` file manually, you are supposed to use `matrix_synapse_configuration_extension_yaml`.

Example (`inventory/host_vars/matrix.DOMAIN/vars.yml`):

```yaml
matrix_synapse_configuration_extension_yaml: |
  saml2_config:
    enabled: true
    config_path: "/data/sp_conf.py"
    idp_redirect_url: "https://__KEYCLOAK_SERVER__/auth/realms/__KEYCLOAK_REALM__/protocol/saml"
```

**Comment by hungrymonkey** [comment]
Thanks. I was looking for the path.

**Comment by hungrymonkey** [comment]
Sorry, I keep forgetting it spams. Sorry
