### ISSUE TITLE
Dimension integration - token conflict at startup

### ISSUE THREAD

**Issue by charlesnw1** [spantaleev/matrix-docker-ansible-deploy#575]
Hello,

I followed the instructions at: 

https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/configuring-playbook-dimension.md

This results in:
-- Logs begin at Sun 2020-07-05 15:01:45 UTC. --
Jul 12 02:56:53 tsys-vps-matrix matrix-dimension[27671]: Jul-12-2020 02:56:53.781 +00:00 info [BotSdk-MatrixLiteClient (REQ-1)] GET http://matrix-synapse:8008/_matrix/client/r0/account/whoami
Jul 12 02:56:53 tsys-vps-matrix matrix-dimension[27671]: Jul-12-2020 02:56:53.807 +00:00 info [BotSdk-MatrixLiteClient (REQ-1 RESP-H200)] {"user_id":"@dimension-admin:turnsys.com"}
Jul 12 02:56:53 tsys-vps-matrix matrix-dimension[27671]: Jul-12-2020 02:56:53.812 +00:00 verbose [DimensionStore [SQL]] Executing (default): SELECT `userId`, `isSelfBot` FROM `dimension_users` AS `User` WHERE `User`.`userId` = '@dimension-admin:turnsys.com' AND `User`.`isSelfBot` = 0;
Jul 12 02:56:53 tsys-vps-matrix matrix-dimension[27671]: Jul-12-2020 02:56:53.816 +00:00 error [index] The access token configured for Dimension belongs to a user which is also a user known to Dimension. This usually indicates that the access token is not a dedicated user account for Dimension. To prevent potential confusion to this user, Dimension will refuse to start until the access token given belongs to a dedicated user.
Jul 12 02:56:53 tsys-vps-matrix matrix-dimension[27671]: Error: Access token belongs to a real user. See logs for details.
Jul 12 02:56:53 tsys-vps-matrix matrix-dimension[27671]:     at /home/node/matrix-dimension/build/app/index.js:40:19
Jul 12 02:56:53 tsys-vps-matrix matrix-dimension[27671]:     at Generator.next (<anonymous>)
Jul 12 02:56:53 tsys-vps-matrix matrix-dimension[27671]:     at fulfilled (/home/node/matrix-dimension/build/app/index.js:4:58)
Jul 12 02:56:54 tsys-vps-matrix systemd[1]: matrix-dimension.service: Main process exited, code=exited, status=1/FAILURE
Jul 12 02:56:54 tsys-vps-matrix systemd[1]: matrix-dimension.service: Failed with result 'exit-code'.
^C

I did a decent amount of googling for various strings, and didn’t find anyone else reporting the issue. If it’s a DUP, please forgive me and point me at another issue.

Thank you for this amazing work!

**Comment by charlesnw1** [comment]
Aha! I had included the dimension bot user as an admin. That is not allowed. removing that, everything worked.
