### ISSUE TITLE
Matrix Dimension Errors

### ISSUE THREAD

**Issue by hungrymonkey** [spantaleev/matrix-docker-ansible-deploy#593]
```
Jul 19 07:15:06 ip-172-31-34-7 matrix-dimension[1738]: Jul-19-2020 07:15:06.895 +00:00 info [index] Starting dimension v1.0.0-db22981
Jul 19 07:15:06 ip-172-31-34-7 matrix-dimension[1738]: Jul-19-2020 07:15:06.905 +00:00 info [DimensionStore] Updating schema...
Jul 19 07:15:07 ip-172-31-34-7 matrix-dimension[1738]: Jul-19-2020 07:15:07.170 +00:00 verbose [DimensionStore [SQL]] Executing (default): CREATE TABLE IF NOT EXISTS `SequelizeMeta` (`name` VARCHAR(255) NOT NULL UNIQUE PRIMARY KEY);
Jul 19 07:15:07 ip-172-31-34-7 matrix-dimension[1738]: Jul-19-2020 07:15:07.238 +00:00 verbose [DimensionStore [SQL]] Executing (default): PRAGMA INDEX_LIST(`SequelizeMeta`)
Jul 19 07:15:07 ip-172-31-34-7 matrix-dimension[1738]: Jul-19-2020 07:15:07.274 +00:00 verbose [DimensionStore [SQL]] Executing (default): PRAGMA INDEX_INFO(`sqlite_autoindex_SequelizeMeta_1`)
Jul 19 07:15:07 ip-172-31-34-7 matrix-dimension[1738]: Jul-19-2020 07:15:07.333 +00:00 verbose [DimensionStore [SQL]] Executing (default): SELECT `name` FROM `SequelizeMeta` AS `SequelizeMeta` ORDER BY `SequelizeMeta`.`name` ASC;
Jul 19 07:15:08 ip-172-31-34-7 matrix-dimension[1738]: Jul-19-2020 07:15:08.396 +00:00 info [Webserver] Registered route: /api/v1/scalar/register
Jul 19 07:15:08 ip-172-31-34-7 matrix-dimension[1738]: Jul-19-2020 07:15:08.403 +00:00 info [Webserver] Registered route: /api/v1/scalar/account
Jul 19 07:15:08 ip-172-31-34-7 matrix-dimension[1738]: Jul-19-2020 07:15:08.404 +00:00 info [Webserver] Registered route: /api/v1/scalar/terms
Jul 19 07:15:08 ip-172-31-34-7 matrix-dimension[1738]: Jul-19-2020 07:15:08.405 +00:00 info [Webserver] Registered route: /api/v1/scalar/ping
Jul 19 07:15:08 ip-172-31-34-7 matrix-dimension[1738]: Jul-19-2020 07:15:08.405 +00:00 info [Webserver] Registered route: /api/v1/scalar/widgets/title_lookup
Jul 19 07:15:08 ip-172-31-34-7 matrix-dimension[1738]: Jul-19-2020 07:15:08.406 +00:00 info [Webserver] Registered route: /api/v1/dimension/gitter/room/:roomId/link
Jul 19 07:15:08 ip-172-31-34-7 matrix-dimension[1738]: Jul-19-2020 07:15:08.406 +00:00 info [Webserver] Registered route: /api/v1/dimension/health/heartbeat
Jul 19 07:15:08 ip-172-31-34-7 matrix-dimension[1738]: Jul-19-2020 07:15:08.409 +00:00 info [Webserver] Registered route: /api/v1/dimension/integrations/room/:roomId
Jul 19 07:15:08 ip-172-31-34-7 matrix-dimension[1738]: Jul-19-2020 07:15:08.411 +00:00 info [Webserver] Registered route: /api/v1/dimension/integrations/room/:roomId/integrations/:category/:type
Jul 19 07:15:08 ip-172-31-34-7 matrix-dimension[1738]: Jul-19-2020 07:15:08.412 +00:00 info [Webserver] Registered route: /api/v1/dimension/integrations/room/:roomId/integrations/:category/:type/config
Jul 19 07:15:08 ip-172-31-34-7 matrix-dimension[1738]: Jul-19-2020 07:15:08.413 +00:00 info [Webserver] Registered route: /api/v1/dimension/integrations/:category/:type
Jul 19 07:15:08 ip-172-31-34-7 matrix-dimension[1738]: Jul-19-2020 07:15:08.413 +00:00 info [Webserver] Registered route: /api/v1/dimension/irc/:networkId/channel/:channel/ops
Jul 19 07:15:08 ip-172-31-34-7 matrix-dimension[1738]: Jul-19-2020 07:15:08.416 +00:00 info [Webserver] Registered route: /api/v1/dimension/irc/:networkId/channel/:channel/link/:roomId
Jul 19 07:15:08 ip-172-31-34-7 matrix-dimension[1738]: Jul-19-2020 07:15:08.423 +00:00 info [Webserver] Registered route: /api/v1/dimension/irc/:networkId/channel/:channel/unlink/:roomId
Jul 19 07:15:08 ip-172-31-34-7 matrix-dimension[1738]: Jul-19-2020 07:15:08.424 +00:00 info [Webserver] Registered route: /api/v1/dimension/media/thumbnail/:serverName/:contentId
Jul 19 07:15:08 ip-172-31-34-7 matrix-dimension[1738]: Jul-19-2020 07:15:08.425 +00:00 info [Webserver] Registered route: /api/v1/dimension/slack/room/:roomId/link
Jul 19 07:15:08 ip-172-31-34-7 matrix-dimension[1738]: Jul-19-2020 07:15:08.425 +00:00 info [Webserver] Registered route: /api/v1/dimension/slack/teams
Jul 19 07:15:08 ip-172-31-34-7 matrix-dimension[1738]: Jul-19-2020 07:15:08.426 +00:00 info [Webserver] Registered route: /api/v1/dimension/slack/teams/:teamId/channels
Jul 19 07:15:08 ip-172-31-34-7 matrix-dimension[1738]: Jul-19-2020 07:15:08.427 +00:00 info [Webserver] Registered route: /api/v1/dimension/slack/auth
Jul 19 07:15:08 ip-172-31-34-7 matrix-dimension[1738]: Jul-19-2020 07:15:08.428 +00:00 info [Webserver] Registered route: /api/v1/dimension/stickers/config
Jul 19 07:15:08 ip-172-31-34-7 matrix-dimension[1738]: Jul-19-2020 07:15:08.428 +00:00 info [Webserver] Registered route: /api/v1/dimension/stickers/packs
Jul 19 07:15:08 ip-172-31-34-7 matrix-dimension[1738]: Jul-19-2020 07:15:08.431 +00:00 info [Webserver] Registered route: /api/v1/dimension/stickers/packs/:packId/selected
```

**Comment by hungrymonkey** [comment]
```
Jul 19 07:15:08 ip-172-31-34-7 matrix-dimension[1738]: Jul-19-2020 07:15:08.556 +00:00 info [Webserver] Registered route: /_matrix/integrations/v1/terms
Jul 19 07:15:08 ip-172-31-34-7 matrix-dimension[1738]: Jul-19-2020 07:15:08.559 +00:00 info [Webserver] Registered route: /.well-known/matrix/integrations
Jul 19 07:15:08 ip-172-31-34-7 matrix-dimension[1738]: Jul-19-2020 07:15:08.562 +00:00 info [Webserver] API and UI listening on 0.0.0.0:8184
Jul 19 07:15:08 ip-172-31-34-7 matrix-dimension[1738]: Jul-19-2020 07:15:08.570 +00:00 info [BotSdk-MatrixLiteClient (REQ-1)] GET http://matrix-synapse:8008/_matrix/client/r0/account/whoami
Jul 19 07:15:08 ip-172-31-34-7 matrix-dimension[1738]: Jul-19-2020 07:15:08.667 +00:00 error [BotSdk-MatrixLiteClient (REQ-1)] connect ECONNREFUSED 172.18.0.12:8008
Jul 19 07:15:08 ip-172-31-34-7 matrix-dimension[1738]: Error: connect ECONNREFUSED 172.18.0.12:8008
Jul 19 07:15:08 ip-172-31-34-7 matrix-dimension[1738]:     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
Jul 19 07:15:08 ip-172-31-34-7 matrix-dimension[1738]: { Error: connect ECONNREFUSED 172.18.0.12:8008
Jul 19 07:15:08 ip-172-31-34-7 matrix-dimension[1738]:     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
Jul 19 07:15:08 ip-172-31-34-7 matrix-dimension[1738]:   errno: 'ECONNREFUSED',
Jul 19 07:15:08 ip-172-31-34-7 matrix-dimension[1738]:   code: 'ECONNREFUSED',
Jul 19 07:15:08 ip-172-31-34-7 matrix-dimension[1738]:   syscall: 'connect',
Jul 19 07:15:08 ip-172-31-34-7 matrix-dimension[1738]:   address: '172.18.0.12',
Jul 19 07:15:08 ip-172-31-34-7 matrix-dimension[1738]:   port: 8008 }
Jul 19 07:15:09 ip-172-31-34-7 systemd[1]: matrix-dimension.service: Main process exited, code=exited, status=1/FAILURE
Jul 19 07:15:09 ip-172-31-34-7 systemd[1]: matrix-dimension.service: Failed with result 'exit-code'.
Jul 19 07:15:39 ip-172-31-34-7 systemd[1]: matrix-dimension.service: Service RestartSec=30s expired, scheduling restart.
Jul 19 07:15:39 ip-172-31-34-7 systemd[1]: matrix-dimension.service: Scheduled restart job, restart counter is at 1.
Jul 19 07:15:39 ip-172-31-34-7 systemd[1]: Stopped Matrix Dimension.
Jul 19 07:15:39 ip-172-31-34-7 systemd[1]: Starting Matrix Dimension...
Jul 19 07:15:39 ip-172-31-34-7 matrix-dimension[4653]: Error response from daemon: Cannot kill container: matrix-dimension: No such container: matrix-dimension
Jul 19 07:15:39 ip-172-31-34-7 matrix-dimension[4663]: Error: No such container: matrix-dimension
Jul 19 07:15:39 ip-172-31-34-7 systemd[1]: Started Matrix Dimension.

```

**Comment by hungrymonkey** [comment]
```
Jul 19 07:15:42 ip-172-31-34-7 matrix-dimension[4671]: Jul-19-2020 07:15:42.168 +00:00 info [Webserver] Registered route: /_matrix/appservice/r0/room/:alias
Jul 19 07:15:42 ip-172-31-34-7 matrix-dimension[4671]: Jul-19-2020 07:15:42.169 +00:00 info [Webserver] Registered route: /_matrix/appservice/r0/user/:userId
Jul 19 07:15:42 ip-172-31-34-7 matrix-dimension[4671]: Jul-19-2020 07:15:42.169 +00:00 info [Webserver] Registered route: /_matrix/integrations/v1/terms
Jul 19 07:15:42 ip-172-31-34-7 matrix-dimension[4671]: Jul-19-2020 07:15:42.169 +00:00 info [Webserver] Registered route: /.well-known/matrix/integrations
Jul 19 07:15:42 ip-172-31-34-7 matrix-dimension[4671]: Jul-19-2020 07:15:42.172 +00:00 info [Webserver] API and UI listening on 0.0.0.0:8184
Jul 19 07:15:42 ip-172-31-34-7 matrix-dimension[4671]: Jul-19-2020 07:15:42.173 +00:00 info [BotSdk-MatrixLiteClient (REQ-1)] GET http://matrix-synapse:8008/_matrix/client/r0/account/whoami
Jul 19 07:15:42 ip-172-31-34-7 matrix-dimension[4671]: Jul-19-2020 07:15:42.203 +00:00 info [BotSdk-MatrixLiteClient (REQ-1 RESP-H401)] {"errcode":"M_UNKNOWN_TOKEN","error":"Unrecognised access token","soft_logout":false}
Jul 19 07:15:42 ip-172-31-34-7 matrix-dimension[4671]: Jul-19-2020 07:15:42.204 +00:00 error [BotSdk-MatrixLiteClient (REQ-1)] {"errcode":"M_UNKNOWN_TOKEN","error":"Unrecognised access token","soft_logout":false}
Jul 19 07:15:42 ip-172-31-34-7 matrix-dimension[4671]: IncomingMessage {
Jul 19 07:15:42 ip-172-31-34-7 matrix-dimension[4671]:   _readableState:
Jul 19 07:15:42 ip-172-31-34-7 matrix-dimension[4671]:    ReadableState {
Jul 19 07:15:42 ip-172-31-34-7 matrix-dimension[4671]:      objectMode: false,
Jul 19 07:15:42 ip-172-31-34-7 matrix-dimension[4671]:      highWaterMark: 16384,
Jul 19 07:15:42 ip-172-31-34-7 matrix-dimension[4671]:      buffer: BufferList { head: null, tail: null, length: 0 },
Jul 19 07:15:42 ip-172-31-34-7 matrix-dimension[4671]:      length: 0,
Jul 19 07:15:42 ip-172-31-34-7 matrix-dimension[4671]:      pipes: null,
Jul 19 07:15:42 ip-172-31-34-7 matrix-dimension[4671]:      pipesCount: 0,

```

**Comment by hungrymonkey** [comment]
https://github.com/turt2live/matrix-dimension/issues/267

**Comment by hungrymonkey** [comment]
I needed to use setup-dimension instead of setup-synapse

**Comment by hungrymonkey** [comment]
Sorry, I create an issue on the wrong bug tracker. Opps
