### ISSUE TITLE
Error making Dimension and the Slack appservice work together

### ISSUE THREAD

**Issue by sdurrheimer** [spantaleev/matrix-docker-ansible-deploy#612]
Hello,

I'm trying to link the slack-appservice with dimension in order to be able to configure bridging through the Dimension interface.

In the Dimension admin interface, I'm able to add a Self-hosted slack bridge configuration using the internal URL `http://matrix-appservice-slack:9004`. The configuration is accepted and the Slack bridge button is displayed without warning icon on the main page of Dimension.

But when I click on the button to try to configure the bridge a room, I get the `Error getting Slack authorization information` error notification in Dimension looping indefinitely.

On the `matrix-appservice-slack` systemd service side, I can see the following errors repeating themselves:

```
Jul 29 12:12:21 ip-10-3-0-207 matrix-appservice-slack[3048]: Jul-29 12:12:21.678 INFO Provisioning Received a _matrix/provision request for authurl
Jul 29 12:12:21 ip-10-3-0-207 matrix-appservice-slack[3048]: Jul-29 12:12:21.679 INFO bridge ::ffff:172.18.0.13 - - [29/Jul/2020:12:12:21 +0000] "POST /_matrix/provision/authurl HTTP/1.1" 400 48 "-" "-"
Jul 29 12:12:21 ip-10-3-0-207 matrix-appservice-slack[3048]: Jul-29 12:12:21.702 INFO Provisioning Received a _matrix/provision request for getbotid
Jul 29 12:12:21 ip-10-3-0-207 matrix-appservice-slack[3048]: Jul-29 12:12:21.704 INFO bridge ::ffff:172.18.0.13 - - [29/Jul/2020:12:12:21 +0000] "POST /_matrix/provision/getbotid HTTP/1.1" 200 38 "-" "-"
Jul 29 12:12:21 ip-10-3-0-207 matrix-appservice-slack[3048]: Jul-29 12:12:21.710 INFO Provisioning Received a _matrix/provision request for getlink
Jul 29 12:12:21 ip-10-3-0-207 matrix-appservice-slack[3048]: Jul-29 12:12:21.711 INFO bridge ::ffff:172.18.0.13 - - [29/Jul/2020:12:12:21 +0000] "POST /_matrix/provision/getlink HTTP/1.1" 404 26 "-" "-"
Jul 29 12:12:22 ip-10-3-0-207 matrix-appservice-slack[3048]: Jul-29 12:12:22.642 INFO Provisioning Received a _matrix/provision request for teams
Jul 29 12:12:22 ip-10-3-0-207 matrix-appservice-slack[3048]: Jul-29 12:12:22.646 INFO bridge ::ffff:172.18.0.13 - - [29/Jul/2020:12:12:22 +0000] "POST /_matrix/provision/teams HTTP/1.1" 500 38 "-" "-"
Jul 29 12:12:22 ip-10-3-0-207 matrix-appservice-slack[3048]: Jul-29 12:12:22.648 ERROR Provisioning Provisioning command threw an error: Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
Jul 29 12:12:22 ip-10-3-0-207 matrix-appservice-slack[3048]:     at ServerResponse.setHeader (_http_outgoing.js:485:11)
Jul 29 12:12:22 ip-10-3-0-207 matrix-appservice-slack[3048]:     at ServerResponse.header (/usr/src/app/node_modules/express/lib/response.js:771:10)
Jul 29 12:12:22 ip-10-3-0-207 matrix-appservice-slack[3048]:     at ServerResponse.send (/usr/src/app/node_modules/express/lib/response.js:170:12)
Jul 29 12:12:22 ip-10-3-0-207 matrix-appservice-slack[3048]:     at ServerResponse.json (/usr/src/app/node_modules/express/lib/response.js:267:15)
Jul 29 12:12:22 ip-10-3-0-207 matrix-appservice-slack[3048]:     at /usr/src/app/lib/Main.js:989:29
Jul 29 12:12:22 ip-10-3-0-207 matrix-appservice-slack[3048]:     at tryCatcher (/usr/src/app/node_modules/matrix-appservice-bridge/node_modules/bluebird/js/main/util.js:26:23)
Jul 29 12:12:22 ip-10-3-0-207 matrix-appservice-slack[3048]:     at Promise._settlePromiseFromHandler (/usr/src/app/node_modules/matrix-appservice-bridge/node_modules/bluebird/js/main/promise.js:510:31)
Jul 29 12:12:22 ip-10-3-0-207 matrix-appservice-slack[3048]:     at Promise._settlePromiseAt (/usr/src/app/node_modules/matrix-appservice-bridge/node_modules/bluebird/js/main/promise.js:584:18)
Jul 29 12:12:22 ip-10-3-0-207 matrix-appservice-slack[3048]:     at Promise._settlePromises (/usr/src/app/node_modules/matrix-appservice-bridge/node_modules/bluebird/js/main/promise.js:700:14)
Jul 29 12:12:22 ip-10-3-0-207 matrix-appservice-slack[3048]:     at Async._drainQueue (/usr/src/app/node_modules/matrix-appservice-bridge/node_modules/bluebird/js/main/async.js:123:16)
Jul 29 12:12:22 ip-10-3-0-207 matrix-appservice-slack[3048]:     at Async._drainQueues (/usr/src/app/node_modules/matrix-appservice-bridge/node_modules/bluebird/js/main/async.js:133:10)
Jul 29 12:12:22 ip-10-3-0-207 matrix-appservice-slack[3048]:     at Immediate.Async.drainQueues [as _onImmediate] (/usr/src/app/node_modules/matrix-appservice-bridge/node_modules/bluebird/js/main/async.js:15:14)
Jul 29 12:12:22 ip-10-3-0-207 matrix-appservice-slack[3048]:     at processImmediate (internal/timers.js:439:21)
Jul 29 12:12:22 ip-10-3-0-207 matrix-appservice-slack[3048]: Jul-29 12:12:22.654 ERROR Provisioning Provisioning command failed: Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
Jul 29 12:12:22 ip-10-3-0-207 matrix-appservice-slack[3048]:     at ServerResponse.setHeader (_http_outgoing.js:485:11)
Jul 29 12:12:22 ip-10-3-0-207 matrix-appservice-slack[3048]:     at ServerResponse.header (/usr/src/app/node_modules/express/lib/response.js:771:10)
Jul 29 12:12:22 ip-10-3-0-207 matrix-appservice-slack[3048]:     at ServerResponse.send (/usr/src/app/node_modules/express/lib/response.js:170:12)
Jul 29 12:12:22 ip-10-3-0-207 matrix-appservice-slack[3048]:     at ServerResponse.json (/usr/src/app/node_modules/express/lib/response.js:267:15)
Jul 29 12:12:22 ip-10-3-0-207 matrix-appservice-slack[3048]:     at /usr/src/app/lib/Provisioning.js:30:37
Jul 29 12:12:22 ip-10-3-0-207 matrix-appservice-slack[3048]:     at tryCatcher (/usr/src/app/node_modules/bluebird/js/release/util.js:16:23)
Jul 29 12:12:22 ip-10-3-0-207 matrix-appservice-slack[3048]:     at Promise._settlePromiseFromHandler (/usr/src/app/node_modules/bluebird/js/release/promise.js:517:31)
Jul 29 12:12:22 ip-10-3-0-207 matrix-appservice-slack[3048]:     at Promise._settlePromise (/usr/src/app/node_modules/bluebird/js/release/promise.js:574:18)
Jul 29 12:12:22 ip-10-3-0-207 matrix-appservice-slack[3048]:     at Promise._settlePromise0 (/usr/src/app/node_modules/bluebird/js/release/promise.js:619:10)
Jul 29 12:12:22 ip-10-3-0-207 matrix-appservice-slack[3048]:     at Promise._settlePromises (/usr/src/app/node_modules/bluebird/js/release/promise.js:695:18)
Jul 29 12:12:22 ip-10-3-0-207 matrix-appservice-slack[3048]:     at _drainQueueStep (/usr/src/app/node_modules/bluebird/js/release/async.js:138:12)
Jul 29 12:12:22 ip-10-3-0-207 matrix-appservice-slack[3048]:     at _drainQueue (/usr/src/app/node_modules/bluebird/js/release/async.js:131:9)
Jul 29 12:12:22 ip-10-3-0-207 matrix-appservice-slack[3048]:     at Async._drainQueues (/usr/src/app/node_modules/bluebird/js/release/async.js:147:5)
Jul 29 12:12:22 ip-10-3-0-207 matrix-appservice-slack[3048]:     at Immediate.Async.drainQueues [as _onImmediate] (/usr/src/app/node_modules/bluebird/js/release/async.js:17:14)
Jul 29 12:12:22 ip-10-3-0-207 matrix-appservice-slack[3048]:     at processImmediate (internal/timers.js:439:21)
Jul 29 12:12:22 ip-10-3-0-207 matrix-appservice-slack[3048]: Unhandled rejection Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
Jul 29 12:12:22 ip-10-3-0-207 matrix-appservice-slack[3048]:     at ServerResponse.setHeader (_http_outgoing.js:485:11)
Jul 29 12:12:22 ip-10-3-0-207 matrix-appservice-slack[3048]:     at ServerResponse.header (/usr/src/app/node_modules/express/lib/response.js:771:10)
Jul 29 12:12:22 ip-10-3-0-207 matrix-appservice-slack[3048]:     at ServerResponse.send (/usr/src/app/node_modules/express/lib/response.js:170:12)
Jul 29 12:12:22 ip-10-3-0-207 matrix-appservice-slack[3048]:     at ServerResponse.json (/usr/src/app/node_modules/express/lib/response.js:267:15)
Jul 29 12:12:22 ip-10-3-0-207 matrix-appservice-slack[3048]:     at /usr/src/app/lib/Provisioning.js:45:29
Jul 29 12:12:22 ip-10-3-0-207 matrix-appservice-slack[3048]:     at tryCatcher (/usr/src/app/node_modules/bluebird/js/release/util.js:16:23)
Jul 29 12:12:22 ip-10-3-0-207 matrix-appservice-slack[3048]:     at Promise._settlePromiseFromHandler (/usr/src/app/node_modules/bluebird/js/release/promise.js:517:31)
Jul 29 12:12:22 ip-10-3-0-207 matrix-appservice-slack[3048]:     at Promise._settlePromise (/usr/src/app/node_modules/bluebird/js/release/promise.js:574:18)
Jul 29 12:12:22 ip-10-3-0-207 matrix-appservice-slack[3048]:     at Promise._settlePromise0 (/usr/src/app/node_modules/bluebird/js/release/promise.js:619:10)
Jul 29 12:12:22 ip-10-3-0-207 matrix-appservice-slack[3048]:     at Promise._settlePromises (/usr/src/app/node_modules/bluebird/js/release/promise.js:695:18)
Jul 29 12:12:22 ip-10-3-0-207 matrix-appservice-slack[3048]:     at _drainQueueStep (/usr/src/app/node_modules/bluebird/js/release/async.js:138:12)
Jul 29 12:12:22 ip-10-3-0-207 matrix-appservice-slack[3048]:     at _drainQueue (/usr/src/app/node_modules/bluebird/js/release/async.js:131:9)
Jul 29 12:12:22 ip-10-3-0-207 matrix-appservice-slack[3048]:     at Async._drainQueues (/usr/src/app/node_modules/bluebird/js/release/async.js:147:5)
Jul 29 12:12:22 ip-10-3-0-207 matrix-appservice-slack[3048]:     at Immediate.Async.drainQueues [as _onImmediate] (/usr/src/app/node_modules/bluebird/js/release/async.js:17:14)
Jul 29 12:12:22 ip-10-3-0-207 matrix-appservice-slack[3048]:     at processImmediate (internal/timers.js:439:21)
```

Is the link between Dimension and the slack bridge supposed to work with this playbook?

**Comment by sdurrheimer** [comment]
On Dimension side, I was able to find those logs that might be a hint to solve the issue:

```
Jul 29 14:17:35 ip-10-3-0-207 matrix-dimension[29131]: Jul-29-2020 14:17:35.773 +00:00 verbose [DimensionStore [SQL]] Executing (default): SELECT `id`, `upstreamId`, `provisionUrl`, `isEnabled` FROM `dimension_slack_bridges` AS `SlackBridgeRecord` WHERE `SlackBridgeRecord`.`isEnabled` = 1;
Jul 29 14:17:35 ip-10-3-0-207 matrix-dimension[29131]: Jul-29-2020 14:17:35.775 +00:00 info [SlackBridge] Doing provision Slack Bridge request: http://matrix-appservice-slack:9004/_matrix/provision/authurl
Jul 29 14:17:35 ip-10-3-0-207 matrix-dimension[29131]: Jul-29-2020 14:17:35.778 +00:00 error [SlackBridge] Got status code 400 when calling http://matrix-appservice-slack:9004/_matrix/provision/authurl
Jul 29 14:17:35 ip-10-3-0-207 matrix-dimension[29131]: Jul-29-2020 14:17:35.778 +00:00 error [SlackBridge] {"error":"OAuth2 not configured on this bridge"}
Jul 29 14:17:35 ip-10-3-0-207 matrix-dimension[29131]: Jul-29-2020 14:17:35.778 +00:00 error [SlackBridge] {"body":{"error":"OAuth2 not configured on this bridge"},"status":400}
Jul 29 14:17:35 ip-10-3-0-207 matrix-dimension[29131]: Jul-29-2020 14:17:35.779 +00:00 error [DimensionSlackService] {"body":{"error":"OAuth2 not configured on this bridge"},"status":400}
```

I can see a Oauth2 reference in the Dimension \[config sample\](https://github.com/matrix-org/matrix-appservice-slack/blob/develop/config/config.sample.yaml#L27-L32)  
  
```
oauth2:
  client_id: ""
  client_secret: ""
  # A prefix similar to inbound_uri_prefix for oauth2 requests. inbound_uri_prefix will be used if this is not set
  # Optional
  redirect_prefix: "https://my.server.here:9898/mycustomoauthendpoint"
```

Which doesn't seem to be handle by the playbook.
