### ISSUE TITLE
Setting matrix_synapse_federation_domain_whitelist to [] generates invalid YAML

### ISSUE THREAD

**Issue by TheLastProject** [spantaleev/matrix-docker-ansible-deploy#78]
The documentation states that you can set matrix_synapse_federation_domain_whitelist to [] to disable federation:

https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/906942f304bc89b88672166357f797dcdd65c01e/roles/matrix-synapse/defaults/main.yml#L93-L96

However, if you actually do so, invalid YAML gets generated into homeserver.yaml:
```
federation_domain_whitelist:
[]
```

This means that matrix-synapse fails to start:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/site-packages/synapse/app/homeserver.py", line 576, in <module>
    main()
  File "/usr/local/lib/python3.6/site-packages/synapse/app/homeserver.py", line 571, in main
    hs = setup(sys.argv[1:])
  File "/usr/local/lib/python3.6/site-packages/synapse/app/homeserver.py", line 312, in setup
    config_options,
  File "/usr/local/lib/python3.6/site-packages/synapse/config/_base.py", line 356, in load_or_generate_config
    generate_keys=generate_keys,
  File "/usr/local/lib/python3.6/site-packages/synapse/config/_base.py", line 374, in read_config_files
    yaml_config = self.read_config_file(config_file)
  File "/usr/local/lib/python3.6/site-packages/synapse/config/_base.py", line 140, in read_config_file
    return yaml.load(file_stream)
  File "/usr/local/lib/python3.6/site-packages/yaml/__init__.py", line 72, in load
    return loader.get_single_data()
  File "/usr/local/lib/python3.6/site-packages/yaml/constructor.py", line 35, in get_single_data
    node = self.get_single_node()
  File "/usr/local/lib/python3.6/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/usr/local/lib/python3.6/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/usr/local/lib/python3.6/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/local/lib/python3.6/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/local/lib/python3.6/site-packages/yaml/composer.py", line 64, in compose_node
    if self.check_event(AliasEvent):
  File "/usr/local/lib/python3.6/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/usr/local/lib/python3.6/site-packages/yaml/parser.py", line 449, in parse_block_mapping_value
    if not self.check_token(KeyToken, ValueToken, BlockEndToken):
  File "/usr/local/lib/python3.6/site-packages/yaml/scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "/usr/local/lib/python3.6/site-packages/yaml/scanner.py", line 159, in fetch_more_tokens
    self.stale_possible_simple_keys()
  File "/usr/local/lib/python3.6/site-packages/yaml/scanner.py", line 289, in stale_possible_simple_keys
    "could not find expected ':'", self.get_mark())
yaml.scanner.ScannerError: while scanning a simple key
  in "/data/homeserver.yaml", line 123, column 1
could not find expected ':'
  in "/data/homeserver.yaml", line 128, column 1
Traceback (most recent call last):
  File "/start.py", line 66, in <module>
    subprocess.check_output(args + ["--generate-keys"])
  File "/usr/local/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/local/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['python', '-m', 'synapse.app.homeserver', '--config-path', '/data/homeserver.yaml', '--generate-keys']' returned non-zero exit status 1.
```

**Comment by spantaleev** [comment]
Good catch! It's fixed now.
