### ISSUE TITLE
Synapse crahses and gets reacreated continuously

### ISSUE THREAD

**Issue by short-circuit** [spantaleev/matrix-docker-ansible-deploy#782]
My matrix-synapse container is crashing continuously with the following log content:
```
matrix-synapse[1087791]: twisted.internet.error.CannotListenError: Couldn't listen on :::8008: [Errno 97] Address family not supported by protocol.
matrix-synapse[1087791]: During handling of the above exception, another exception occurred:
matrix-synapse[1087791]: Traceback (most recent call last):
matrix-synapse[1087791]:   File "/usr/local/lib/python3.8/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
matrix-synapse[1087791]:     result = g.send(result)
matrix-synapse[1087791]:   File "/usr/local/lib/python3.8/site-packages/synapse/app/homeserver.py", line 429, in start
matrix-synapse[1087791]:     _base.start(hs, config.listeners)
matrix-synapse[1087791]:   File "/usr/local/lib/python3.8/site-packages/synapse/app/_base.py", line 308, in start
matrix-synapse[1087791]:     sys.exit(1)
matrix-synapse[1087791]: SystemExit: 1
```

It gets recreated continuously without ever being able to actually start.

Also getting the following warning at container start:
```
systemd[1]: Starting Synapse server...
matrix-synapse[1093761]: WARNING: Error loading config file: .dockercfg: $HOME is not defined
matrix-synapse[1093761]: Error response from daemon: Cannot kill container: matrix-synapse: No such container: matrix-synapse
matrix-synapse[1093791]: WARNING: Error loading config file: .dockercfg: $HOME is not defined
matrix-synapse[1093791]: Error: No such container: matrix-synapse
systemd[1]: Started Synapse server.
matrix-synapse[1093838]: WARNING: Error loading config file: .dockercfg: $HOME is not defined
```

Most probably something went wrong when ansible created the user `matrix`, but I am not fluent with the tool so I cannot be sure.

**Comment by spantaleev** [comment]
What's your `vars.yml` file like? Have you fiddled with the ports that Synapse uses?

**Comment by short-circuit** [comment]
> What's your `vars.yml` file like? Have you fiddled with the ports that Synapse uses?

I am using the configuration sample for traefik, not much else.

```
# Example value: example.com
matrix_domain: [redacted]

# Example value: someone@example.com
matrix_ssl_lets_encrypt_support_email:  [redacted]

# A shared secret (between Coturn and Synapse) used for authentication.
# You can put any string here, but generating a strong one is preferred (e.g. `pwgen -s 64 1`).
matrix_coturn_turn_static_auth_secret:  [redacted]

# A secret used to protect access keys issued by the server.
# You can put any string here, but generating a strong one is preferred (e.g. `pwgen -s 64 1`).
matrix_synapse_macaroon_secret_key:  [redacted]

# Disable generation and retrieval of SSL certs
matrix_ssl_retrieval_method: none

# Configure Nginx to only use plain HTTP
matrix_nginx_proxy_https_enabled: false

# Don't bind any HTTP or federation port to the host
# (Traefik will proxy directly into the containers)
matrix_nginx_proxy_container_http_host_bind_port: ''
matrix_nginx_proxy_container_federation_host_bind_port: ''

# Disable Coturn because it needs SSL certs
# (Clients can, though exposing IP address, use Matrix.org TURN)
matrix_coturn_enabled: false

# All containers need to be on the same Docker network as Traefik
# (This network should already exist and Traefik should be using this network)
matrix_docker_network: 'web'

matrix_nginx_proxy_container_extra_arguments:
  # May be unnecessary depending on Traefik config, but can't hurt
  - '--label "traefik.enable=true"'

  # The Nginx proxy container will receive traffic from these subdomains
  - '--label "traefik.http.routers.matrix-nginx-proxy.rule=Host(`{{ matrix_server_fqn_matrix }}`,`{{ matrix_server_fqn_element }}`,`{{ matrix_server_fqn_dimension }}`,`{{ matrix_server_fqn_jitsi }}`)"'

  # (The 'web-secure' entrypoint must bind to port 443 in Traefik config)
  - '--label "traefik.http.routers.matrix-nginx-proxy.entrypoints=web-secured"'

  # (The 'default' certificate resolver must be defined in Traefik config)
  - '--label "traefik.http.routers.matrix-nginx-proxy.tls.certResolver=domaintls"'

  # The Nginx proxy container uses port 8080 internally
  - '--label "traefik.http.services.matrix-nginx-proxy.loadbalancer.server.port=8080"'

matrix_synapse_container_extra_arguments:
  # May be unnecessary depending on Traefik config, but can't hurt
  - '--label "traefik.enable=true"'

  # The Synapse container will receive traffic from this subdomain
  - '--label "traefik.http.routers.matrix-synapse.rule=Host(`{{ matrix_server_fqn_matrix }}`)"'

  # (The 'synapse' entrypoint must bind to port 8448 in Traefik config)
  - '--label "traefik.http.routers.matrix-synapse.entrypoints=synapse"'

  # (The 'default' certificate resolver must be defined in Traefik config)
  - '--label "traefik.http.routers.matrix-synapse.tls.certResolver=domaintls"'

  # The Synapse container uses port 8048 internally
  - '--label "traefik.http.services.matrix-synapse.loadbalancer.server.port=8048"'
```

**Comment by spantaleev** [comment]
What distro is this on?

We do use `::` in `homeserver.yaml` to signify "all interfaces" on all protocols (IPv4 and IPv6). See here: https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/0b260a133f16b89ace38acd5fe1da2f7da28d232/roles/matrix-synapse/templates/synapse/homeserver.yaml.j2#L191-L228

This is the first time someone complains about it failing though.

I guess we could make this configurable. If `0.0.0.0` is used, it should work. You can try modifying `homeservers.yaml.j2` in the playbook manually (for now) to see if it helps you.

I wonder why we need to do this though. Have you somehow ripped IPv6 out of your system completely? How?

**Comment by short-circuit** [comment]
> I wonder why we need to do this though. Have you somehow ripped IPv6 out of your system completely? How?

I am running Ubuntu Server 20.04.
Yeah IPv6 is completely disabled on my system for security reasons as it would trigger IP address leaking over VPN services.
I do not have this kind of problem with any other container running on `::` interfaces though, which was confusing. 

> I guess we could make this configurable. If `0.0.0.0` is used, it should work. You can try modifying `homeservers.yaml.j2` in the playbook manually (for now) to see if it helps you.

I just stopped all containers, ran the setup-all tag and started the whole stack again after doing this.
Apparently now the matrix-synapse container is happy and healthy.
![chrome_sIlgvgTNBJ](https://user-images.githubusercontent.com/4368769/104294723-d68d4000-54bf-11eb-80be-b53a5b6f893f.png)

So maybe a variable in `vars.yaml` to deactivate IPv6 altogether or directly give the user the possibility to decide the binding address(es)?


Now I need to see why the webserver is not available at all, even though everything should be configured correctly for traefik.
