### ISSUE TITLE
Signal not working

### ISSUE THREAD

**Issue by McL0v1n** [spantaleev/matrix-docker-ansible-deploy#826]
I've tried to get the Signal Bridge working on two different servers.
One server has letsencrypt SSL certs
One server is self-signed

Both servers behave in the same way:

Signal bot works, but when going to link it never sends the QR code.

The logs show it generating one, but it never sends through the bot and eventually times out.

**Comment by JonathanReifer** [comment]
Having the same issue.  Appears that the link request is sent (via signald) but there is no reply and then it times out.  Register cmd doesn't work either with the same behavior (message relayed to signald, signald sends out registration request but then it times out).

**Comment by McL0v1n** [comment]
I can't be sure the code even finishes generating. In the logs I see "Generating URI" but thats it.

**Comment by JonathanReifer** [comment]
here's what I get when running signald with the -v flag (and sending the link command to the bot):
20:39:00.604 [socketlistener] INFO  io.finn.signald.SocketHandler - Generating linking URI
20:39:00.605 [socketlistener] DEBUG io.finn.signald.ProtocolLogger - [WebSocketConnection] connect()




20:41:10.855 [OkHttp https://textsecure-service.whispersystems.org/...] DEBUG io.finn.signald.ProtocolLogger - [WebSocketConnection] onFailure()
java.net.SocketTimeoutException: Read timed out
	at java.base/java.net.SocketInputStream.socketRead0(Native Method)
	at java.base/java.net.SocketInputStream.socketRead(Unknown Source)
	at java.base/java.net.SocketInputStream.read(Unknown Source)
	at java.base/java.net.SocketInputStream.read(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketInputRecord.read(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketInputRecord.decode(Unknown Source)
	at java.base/sun.security.ssl.SSLTransport.decode(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.kt:367)
	at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.kt:325)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:197)
	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:249)
	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:108)
	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:76)
	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:245)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:82)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
	at io.finn.signald.Manager.lambda$generateSignalServiceConfiguration$0(Manager.java:123)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:197)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:502)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
	Suppressed: java.net.SocketTimeoutException: Read timed out
		... 34 more

20:41:10.860 [OkHttp https://textsecure-service.whispersystems.org/...] DEBUG io.finn.signald.ProtocolLogger - [WebSocketConnection] onClose()
20:41:11.063 [OkHttp https://textsecure-service.whispersystems.org/...] DEBUG io.finn.signald.ProtocolLogger - [WebSocketConnection] connect()

**Comment by McL0v1n** [comment]
From your logs it looks like signal can't connect upstream, so its definitely NOT generating a code.

Since everyone else (NOT via this playbook) is working, i think its an issue with the playbook. I'll dig into configurations and see what I can find

**Comment by JonathanReifer** [comment]
Ok, got the same error using the latest docker image from finn.  Looks like the issue is not related to this playbook.  Tested as follows:
docker pull finn/signald
docker run finn/signald
In separate window:
docker ps (note cointainerID of finn/signald
docker exec -it -u root CONTAINERID /bin/bash
apt install netcat-openbsd
nc -U /signald/signald.sock
in nc: {"type": "link", "deviceName": "your-device-name"}

I'm wondering if this driven by signald hitting a captcha or something similar ( there's a closed issue listed here: https://gitlab.com/signald/signald/-/issues/8 )

**Comment by JonathanReifer** [comment]
After further testing, I can confirm that this is an issue in signald that's based on the ip address signald is using to connect to signal's servers.  It appears that if you're using certain cloud providers the signal services timeout the request (perhaps they're presenting a captcha that signald doesn't know how to handle) but if you use a different ip (such as one of a regular isp) signald is able to link as expected.

This issue can likely get closed out here (for further work on the signald project).  Only thing that would be nice on this side would be more informative error reporting but as signald is not reporting the error and instead the link request is just timing out, I'm not sure what else can be at by mautrix-signal (or this playbook).

**Comment by McL0v1n** [comment]
Agreed.
FYI, the DNS servers i'm using are cloudflares
I'll test with Google
