### ISSUE TITLE
LetsEncrypt auto renewal issue

### ISSUE THREAD

**Issue by Broglah1** [spantaleev/matrix-docker-ansible-deploy#976]
Can't seem to get the certificates to renew - ran "systemctl status matrix-ssl-lets-encrypt-certificates-renew.service" - manually too

**_log file: /matrix/ssl/log/letsencrypt.log_** shows the following
Fetching http://matrix.mydomain.com/.well-known/acme-challenge/7ecLl2_PicCnt3cm0v1g5RbnLh5qht4mjgNJohIFxXk: Timeout during connect (likely firewall problem)

checked firewall that's all open for ports it could possibly use 80, 443, 8080 - (plus additional needed for other matrix related applications) - 8443, 8008, 5349, 3478, 8448, 8432(Discord bot)
https://element.mydomain.com/.well-known/acme-challenge gives nginx 404
https://matrix.mydomain.com/.well-known/acme-challenge redirects to element, but think that's to be expected due to trying with chrome.

**DNS:**

A | matrix | IP-REDACTED | 2 min | DNS only
CNAME | dimension | matrix.mydomain.com | 2 min | DNS only | Edit
CNAME | element | matrix.mydomain.com | 2 min | DNS only | Edit
CNAME | jitsi | matrix.mydomain.com | 2 min | DNS only
SRV | _matrix-identity._tcp | 10 0 443 matrix.mydomain.com

Any help would be greatly appreciated the cert expires on the 16th :(

**last few lines of log:**
2021-04-02 17:41:45,983:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/authz-v3/12036088227 HTTP/1.1" 200 1050
2021-04-02 17:41:45,983:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Fri, 02 Apr 2021 17:41:45 GMT
Content-Type: application/json
Content-Length: 1050
Connection: keep-alive
Boulder-Requester: 109743340
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: 0003KeiKzHuD15mM_8KNtxAGTFuzURDjUo1XrD-kfos3Qq8
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "identifier": {
    "type": "dns",
    "value": "matrix.mydomain.com"
  },
  "status": "invalid",
  "expires": "2021-04-09T17:41:29Z",
  "challenges": [
    {
      "type": "http-01",
      "status": "invalid",
      "error": {
        "type": "urn:ietf:params:acme:error:connection",
        "detail": "Fetching http://matrix.mydomain.com/.well-known/acme-challenge/7ecLl2_PicCnt3cm0v1g5RbnLh5qht4mjgNJohIFxXk: Timeout during connect (likely firewall problem)",
        "status": 400
      },
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/12036088227/fmzSCg",
      "token": "7ecLl2_PicCnt3cm0v1g5RbnLh5qht4mjgNJohIFxXk",
      "validationRecord": [
        {
          "url": "http://matrix.mydomain.com/.well-known/acme-challenge/7ecLl2_PicCnt3cm0v1g5RbnLh5qht4mjgNJohIFxXk",
          "hostname": "matrix.mydomain.com",
          "port": "80",
          "addressesResolved": [
            "MY IP ADDRESS REDACTED"
          ],
          "addressUsed": "MY IP ADDRESS REDACTED"
        }
      ],
      "validated": "2021-04-02T17:41:35Z"
    }
  ]
}
2021-04-02 17:41:45,984:DEBUG:acme.client:Storing nonce: 0003KeiKzHuD15mM_8KNtxAGTFuzURDjUo1XrD-kfos3Qq8
2021-04-02 17:41:45,984:WARNING:certbot._internal.auth_handler:Challenge failed for domain matrix.mydomain.com
2021-04-02 17:41:45,984:INFO:certbot._internal.auth_handler:http-01 challenge for matrix.mydomain.com
2021-04-02 17:41:45,985:DEBUG:certbot._internal.reporter:Reporting to user: The following errors were reported by the server:

Domain: matrix.mydomain.com
Type:   connection
Detail: Fetching http://matrix.mydomain.com/.well-known/acme-challenge/7ecLl2_PicCnt3cm0v1g5RbnLh5qht4mjgNJohIFxXk: Timeout during connect (likely firewall problem)

To fix these errors, please make sure that your domain name was entered correctly and the DNS A/AAAA record(s) for that domain contain(s) the right IP address. Additionally, please check that your computer has a publicly routable IP address and that no firewalls are preventing the server from communicating with the client. If you're using the webroot plugin, you should also verify that you are serving files from the webroot path you provided.
2021-04-02 17:41:45,985:DEBUG:certbot._internal.error_handler:Encountered exception:
Traceback (most recent call last):
  File "/opt/certbot/src/certbot/certbot/_internal/auth_handler.py", line 91, in handle_authorizations
    self._poll_authorizations(authzrs, max_retries, best_effort)
  File "/opt/certbot/src/certbot/certbot/_internal/auth_handler.py", line 180, in _poll_authorizations
    raise errors.AuthorizationError('Some challenges have failed.')
certbot.errors.AuthorizationError: Some challenges have failed.

2021-04-02 17:41:45,985:DEBUG:certbot._internal.error_handler:Calling registered functions
2021-04-02 17:41:45,985:INFO:certbot._internal.auth_handler:Cleaning up challenges
2021-04-02 17:41:45,985:DEBUG:certbot._internal.plugins.standalone:Stopping server at :::8080...
2021-04-02 17:41:46,222:WARNING:certbot._internal.renewal:Attempting to renew cert (matrix.mydomain.com) from /etc/letsencrypt/renewal/matrix.mydomain.com.conf produced an unexpected error: Some challenges have failed.. Skipping.
2021-04-02 17:41:46,222:DEBUG:certbot._internal.renewal:Traceback was:
Traceback (most recent call last):
  File "/opt/certbot/src/certbot/certbot/_internal/renewal.py", line 472, in handle_renewal_request
    main.renew_cert(lineage_config, plugins, renewal_candidate)
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 1234, in renew_cert
    renewed_lineage = _get_and_save_cert(le_client, config, lineage=lineage)
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 123, in _get_and_save_cert
    renewal.renew_cert(config, domains, le_client, lineage)
  File "/opt/certbot/src/certbot/certbot/_internal/renewal.py", line 330, in renew_cert
    new_cert, new_chain, new_key, _ = le_client.obtain_certificate(domains, new_key)
  File "/opt/certbot/src/certbot/certbot/_internal/client.py", line 374, in obtain_certificate
    orderr = self._get_order_and_authorizations(csr.data, self.config.allow_subset_of_names)
  File "/opt/certbot/src/certbot/certbot/_internal/client.py", line 421, in _get_order_and_authorizations
    authzr = self.auth_handler.handle_authorizations(orderr, best_effort)
  File "/opt/certbot/src/certbot/certbot/_internal/auth_handler.py", line 91, in handle_authorizations
    self._poll_authorizations(authzrs, max_retries, best_effort)
  File "/opt/certbot/src/certbot/certbot/_internal/auth_handler.py", line 180, in _poll_authorizations
    raise errors.AuthorizationError('Some challenges have failed.')
certbot.errors.AuthorizationError: Some challenges have failed.

**Comment by Broglah1** [comment]
Never mind turns out it was my firewall.
